// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/unit/job/job.proto

package job

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Keyword              string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Date                 string   `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7561c3149cc207, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Job) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Job) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Job) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "pb.unit.job.Job")
}

func init() { proto.RegisterFile("pb/unit/job/job.proto", fileDescriptor_1e7561c3149cc207) }

var fileDescriptor_1e7561c3149cc207 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x3d, 0x0b, 0xc2, 0x30,
	0x10, 0x40, 0xe9, 0xa7, 0x18, 0xc1, 0xe1, 0x50, 0xc9, 0x28, 0x4e, 0x0e, 0x9a, 0x54, 0xfc, 0x07,
	0x8e, 0x8e, 0x8e, 0x6e, 0x39, 0x13, 0x6a, 0x5a, 0xed, 0xd5, 0x36, 0xa5, 0xf8, 0xef, 0xa5, 0xb1,
	0x82, 0xc3, 0xc1, 0xbd, 0x77, 0x70, 0x3c, 0xb6, 0xac, 0x51, 0x76, 0x95, 0x75, 0xb2, 0x20, 0x1c,
	0x46, 0xd4, 0x0d, 0x39, 0x82, 0x59, 0x8d, 0x62, 0xd0, 0xa2, 0x20, 0xdc, 0xbc, 0x58, 0x74, 0x26,
	0x84, 0x39, 0x0b, 0xad, 0xe6, 0xc1, 0x3a, 0xd8, 0x4e, 0x2f, 0xa1, 0xd5, 0xb0, 0x62, 0x69, 0xeb,
	0x94, 0xeb, 0x5a, 0x1e, 0x7a, 0x37, 0x12, 0x70, 0x36, 0x29, 0xcd, 0xbb, 0xa7, 0x46, 0xf3, 0xc8,
	0x1f, 0x7e, 0x08, 0x0b, 0x96, 0x50, 0x5f, 0x99, 0x86, 0xc7, 0xde, 0x7f, 0x01, 0x80, 0xc5, 0x5a,
	0x39, 0xc3, 0x13, 0x2f, 0xfd, 0x7e, 0x12, 0xd7, 0x5d, 0x6e, 0xdd, 0xbd, 0x43, 0x71, 0xa3, 0xa7,
	0x54, 0xf9, 0xc3, 0x6a, 0x73, 0xc8, 0x32, 0xa9, 0x55, 0xb9, 0x1f, 0xbf, 0xc9, 0xbf, 0x72, 0x4c,
	0x7d, 0xf6, 0xf1, 0x13, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x7b, 0x3a, 0x44, 0xcf, 0x00, 0x00, 0x00,
}
