# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/svc/manager/analyzer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpb/svc/manager/analyzer.proto\x12\x17pb.svc.manager.analyzer\"!\n\x13WhenDoneAnalyzerReq\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x13WhenDoneAnalyzerRes\x12\x0e\n\x06result\x18\x01 \x01(\t\"\"\n\x14WhenStartAnalyzerReq\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x14WhenStartAnalyzerRes\x12\x0e\n\x06result\x18\x01 \x01(\t\"3\n\x18WhenAnalyzerHavingErrReq\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1a\n\x18WhenAnalyzerHavingErrRes2\xf3\x02\n\x0f\x41nalyzerService\x12q\n\x11WhenStartAnalyzer\x12-.pb.svc.manager.analyzer.WhenStartAnalyzerReq\x1a-.pb.svc.manager.analyzer.WhenStartAnalyzerRes\x12n\n\x10WhenDoneAnalyzer\x12,.pb.svc.manager.analyzer.WhenDoneAnalyzerReq\x1a,.pb.svc.manager.analyzer.WhenDoneAnalyzerRes\x12}\n\x15WhenAnalyzerHavingErr\x12\x31.pb.svc.manager.analyzer.WhenAnalyzerHavingErrReq\x1a\x31.pb.svc.manager.analyzer.WhenAnalyzerHavingErrResB:Z8github.com/aglide100/dak-keyword/pb/svc/manager/analyzerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.svc.manager.analyzer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8github.com/aglide100/dak-keyword/pb/svc/manager/analyzer'
  _WHENDONEANALYZERREQ._serialized_start=58
  _WHENDONEANALYZERREQ._serialized_end=91
  _WHENDONEANALYZERRES._serialized_start=93
  _WHENDONEANALYZERRES._serialized_end=130
  _WHENSTARTANALYZERREQ._serialized_start=132
  _WHENSTARTANALYZERREQ._serialized_end=166
  _WHENSTARTANALYZERRES._serialized_start=168
  _WHENSTARTANALYZERRES._serialized_end=206
  _WHENANALYZERHAVINGERRREQ._serialized_start=208
  _WHENANALYZERHAVINGERRREQ._serialized_end=259
  _WHENANALYZERHAVINGERRRES._serialized_start=261
  _WHENANALYZERHAVINGERRRES._serialized_end=287
  _ANALYZERSERVICE._serialized_start=290
  _ANALYZERSERVICE._serialized_end=661
# @@protoc_insertion_point(module_scope)
