# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.svc.manager import manager_pb2 as pb_dot_svc_dot_manager_dot_manager__pb2


class ManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNewJob = channel.unary_unary(
                '/pb.svc.manager.Manager/CreateNewJob',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.CreateNewJobReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.CreateNewJobRes.FromString,
                )
        self.ReRunJob = channel.unary_unary(
                '/pb.svc.manager.Manager/ReRunJob',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.ReRunJobReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.ReRunJobRes.FromString,
                )
        self.GetJobStatus = channel.unary_unary(
                '/pb.svc.manager.Manager/GetJobStatus',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetJobStatusReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetJobStatusRes.FromString,
                )
        self.GetJobList = channel.unary_unary(
                '/pb.svc.manager.Manager/GetJobList',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetJobListReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetJobListRes.FromString,
                )
        self.GetWorkerList = channel.unary_unary(
                '/pb.svc.manager.Manager/GetWorkerList',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetWorkerListReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetWorkerListRes.FromString,
                )
        self.GetArticleInfo = channel.unary_unary(
                '/pb.svc.manager.Manager/GetArticleInfo',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleInfoReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleInfoRes.FromString,
                )
        self.GetArticleList = channel.unary_unary(
                '/pb.svc.manager.Manager/GetArticleList',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleListReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleListRes.FromString,
                )
        self.UpdateWorkerStatus = channel.unary_unary(
                '/pb.svc.manager.Manager/UpdateWorkerStatus',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.UpdateWorkerStatusReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.UpdateWorkerStatusRes.FromString,
                )
        self.UpdateJobStatus = channel.unary_unary(
                '/pb.svc.manager.Manager/UpdateJobStatus',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.UpdateJobStatusReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.UpdateJobStatusRes.FromString,
                )
        self.WhenStartScraper = channel.unary_unary(
                '/pb.svc.manager.Manager/WhenStartScraper',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartScraperReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartScraperRes.FromString,
                )
        self.WhenDoneScraper = channel.unary_unary(
                '/pb.svc.manager.Manager/WhenDoneScraper',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneScraperReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneScraperRes.FromString,
                )
        self.WhenStartAnalyzer = channel.unary_unary(
                '/pb.svc.manager.Manager/WhenStartAnalyzer',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartAnalyzerReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartAnalyzerRes.FromString,
                )
        self.WhenDoneAnalyzer = channel.unary_unary(
                '/pb.svc.manager.Manager/WhenDoneAnalyzer',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneAnalyzerReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneAnalyzerRes.FromString,
                )
        self.WhenScraperHavingErr = channel.unary_unary(
                '/pb.svc.manager.Manager/WhenScraperHavingErr',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenScraperHavingErrReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenScraperHavingErrRes.FromString,
                )
        self.WhenAnalyzerHavingErr = channel.unary_unary(
                '/pb.svc.manager.Manager/WhenAnalyzerHavingErr',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenAnalyzerHavingErrReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenAnalyzerHavingErrRes.FromString,
                )
        self.StopJob = channel.unary_unary(
                '/pb.svc.manager.Manager/StopJob',
                request_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.StopJobReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.StopJobRes.FromString,
                )


class ManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNewJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReRunJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkerList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticleInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticleList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhenStartScraper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhenDoneScraper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhenStartAnalyzer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhenDoneAnalyzer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhenScraperHavingErr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhenAnalyzerHavingErr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNewJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewJob,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.CreateNewJobReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.CreateNewJobRes.SerializeToString,
            ),
            'ReRunJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ReRunJob,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.ReRunJobReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.ReRunJobRes.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetJobStatusReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetJobStatusRes.SerializeToString,
            ),
            'GetJobList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobList,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetJobListReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetJobListRes.SerializeToString,
            ),
            'GetWorkerList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkerList,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetWorkerListReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetWorkerListRes.SerializeToString,
            ),
            'GetArticleInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticleInfo,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleInfoReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleInfoRes.SerializeToString,
            ),
            'GetArticleList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticleList,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleListReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleListRes.SerializeToString,
            ),
            'UpdateWorkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkerStatus,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.UpdateWorkerStatusReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.UpdateWorkerStatusRes.SerializeToString,
            ),
            'UpdateJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJobStatus,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.UpdateJobStatusReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.UpdateJobStatusRes.SerializeToString,
            ),
            'WhenStartScraper': grpc.unary_unary_rpc_method_handler(
                    servicer.WhenStartScraper,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartScraperReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartScraperRes.SerializeToString,
            ),
            'WhenDoneScraper': grpc.unary_unary_rpc_method_handler(
                    servicer.WhenDoneScraper,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneScraperReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneScraperRes.SerializeToString,
            ),
            'WhenStartAnalyzer': grpc.unary_unary_rpc_method_handler(
                    servicer.WhenStartAnalyzer,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartAnalyzerReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartAnalyzerRes.SerializeToString,
            ),
            'WhenDoneAnalyzer': grpc.unary_unary_rpc_method_handler(
                    servicer.WhenDoneAnalyzer,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneAnalyzerReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneAnalyzerRes.SerializeToString,
            ),
            'WhenScraperHavingErr': grpc.unary_unary_rpc_method_handler(
                    servicer.WhenScraperHavingErr,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenScraperHavingErrReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenScraperHavingErrRes.SerializeToString,
            ),
            'WhenAnalyzerHavingErr': grpc.unary_unary_rpc_method_handler(
                    servicer.WhenAnalyzerHavingErr,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenAnalyzerHavingErrReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.WhenAnalyzerHavingErrRes.SerializeToString,
            ),
            'StopJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StopJob,
                    request_deserializer=pb_dot_svc_dot_manager_dot_manager__pb2.StopJobReq.FromString,
                    response_serializer=pb_dot_svc_dot_manager_dot_manager__pb2.StopJobRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.svc.manager.Manager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Manager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNewJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/CreateNewJob',
            pb_dot_svc_dot_manager_dot_manager__pb2.CreateNewJobReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.CreateNewJobRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReRunJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/ReRunJob',
            pb_dot_svc_dot_manager_dot_manager__pb2.ReRunJobReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.ReRunJobRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/GetJobStatus',
            pb_dot_svc_dot_manager_dot_manager__pb2.GetJobStatusReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.GetJobStatusRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/GetJobList',
            pb_dot_svc_dot_manager_dot_manager__pb2.GetJobListReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.GetJobListRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWorkerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/GetWorkerList',
            pb_dot_svc_dot_manager_dot_manager__pb2.GetWorkerListReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.GetWorkerListRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArticleInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/GetArticleInfo',
            pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleInfoReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArticleList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/GetArticleList',
            pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleListReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.GetArticleListRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateWorkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/UpdateWorkerStatus',
            pb_dot_svc_dot_manager_dot_manager__pb2.UpdateWorkerStatusReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.UpdateWorkerStatusRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/UpdateJobStatus',
            pb_dot_svc_dot_manager_dot_manager__pb2.UpdateJobStatusReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.UpdateJobStatusRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WhenStartScraper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/WhenStartScraper',
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartScraperReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartScraperRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WhenDoneScraper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/WhenDoneScraper',
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneScraperReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneScraperRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WhenStartAnalyzer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/WhenStartAnalyzer',
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartAnalyzerReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenStartAnalyzerRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WhenDoneAnalyzer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/WhenDoneAnalyzer',
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneAnalyzerReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenDoneAnalyzerRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WhenScraperHavingErr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/WhenScraperHavingErr',
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenScraperHavingErrReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenScraperHavingErrRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WhenAnalyzerHavingErr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/WhenAnalyzerHavingErr',
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenAnalyzerHavingErrReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.WhenAnalyzerHavingErrRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.svc.manager.Manager/StopJob',
            pb_dot_svc_dot_manager_dot_manager__pb2.StopJobReq.SerializeToString,
            pb_dot_svc_dot_manager_dot_manager__pb2.StopJobRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
