// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/svc/manager/manager.proto

package manager

import (
	context "context"
	fmt "fmt"
	job "github.com/aglide100/dak-keyword/pb/unit/job"
	worker "github.com/aglide100/dak-keyword/pb/unit/worker"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateNewJobReq struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewJobReq) Reset()         { *m = CreateNewJobReq{} }
func (m *CreateNewJobReq) String() string { return proto.CompactTextString(m) }
func (*CreateNewJobReq) ProtoMessage()    {}
func (*CreateNewJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{0}
}

func (m *CreateNewJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewJobReq.Unmarshal(m, b)
}
func (m *CreateNewJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewJobReq.Marshal(b, m, deterministic)
}
func (m *CreateNewJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewJobReq.Merge(m, src)
}
func (m *CreateNewJobReq) XXX_Size() int {
	return xxx_messageInfo_CreateNewJobReq.Size(m)
}
func (m *CreateNewJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewJobReq proto.InternalMessageInfo

func (m *CreateNewJobReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *CreateNewJobReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type CreateNewJobRes struct {
	Keyword              []string `protobuf:"bytes,1,rep,name=keyword,proto3" json:"keyword,omitempty"`
	WorkerId             []string `protobuf:"bytes,2,rep,name=workerId,proto3" json:"workerId,omitempty"`
	JobId                string   `protobuf:"bytes,3,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewJobRes) Reset()         { *m = CreateNewJobRes{} }
func (m *CreateNewJobRes) String() string { return proto.CompactTextString(m) }
func (*CreateNewJobRes) ProtoMessage()    {}
func (*CreateNewJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{1}
}

func (m *CreateNewJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewJobRes.Unmarshal(m, b)
}
func (m *CreateNewJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewJobRes.Marshal(b, m, deterministic)
}
func (m *CreateNewJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewJobRes.Merge(m, src)
}
func (m *CreateNewJobRes) XXX_Size() int {
	return xxx_messageInfo_CreateNewJobRes.Size(m)
}
func (m *CreateNewJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewJobRes proto.InternalMessageInfo

func (m *CreateNewJobRes) GetKeyword() []string {
	if m != nil {
		return m.Keyword
	}
	return nil
}

func (m *CreateNewJobRes) GetWorkerId() []string {
	if m != nil {
		return m.WorkerId
	}
	return nil
}

func (m *CreateNewJobRes) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type GetJobStatusReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobStatusReq) Reset()         { *m = GetJobStatusReq{} }
func (m *GetJobStatusReq) String() string { return proto.CompactTextString(m) }
func (*GetJobStatusReq) ProtoMessage()    {}
func (*GetJobStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{2}
}

func (m *GetJobStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobStatusReq.Unmarshal(m, b)
}
func (m *GetJobStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobStatusReq.Marshal(b, m, deterministic)
}
func (m *GetJobStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobStatusReq.Merge(m, src)
}
func (m *GetJobStatusReq) XXX_Size() int {
	return xxx_messageInfo_GetJobStatusReq.Size(m)
}
func (m *GetJobStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobStatusReq proto.InternalMessageInfo

func (m *GetJobStatusReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetJobStatusReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type GetJobStatusRes struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobStatusRes) Reset()         { *m = GetJobStatusRes{} }
func (m *GetJobStatusRes) String() string { return proto.CompactTextString(m) }
func (*GetJobStatusRes) ProtoMessage()    {}
func (*GetJobStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{3}
}

func (m *GetJobStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobStatusRes.Unmarshal(m, b)
}
func (m *GetJobStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobStatusRes.Marshal(b, m, deterministic)
}
func (m *GetJobStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobStatusRes.Merge(m, src)
}
func (m *GetJobStatusRes) XXX_Size() int {
	return xxx_messageInfo_GetJobStatusRes.Size(m)
}
func (m *GetJobStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobStatusRes proto.InternalMessageInfo

func (m *GetJobStatusRes) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type StopJobReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopJobReq) Reset()         { *m = StopJobReq{} }
func (m *StopJobReq) String() string { return proto.CompactTextString(m) }
func (*StopJobReq) ProtoMessage()    {}
func (*StopJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{4}
}

func (m *StopJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopJobReq.Unmarshal(m, b)
}
func (m *StopJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopJobReq.Marshal(b, m, deterministic)
}
func (m *StopJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopJobReq.Merge(m, src)
}
func (m *StopJobReq) XXX_Size() int {
	return xxx_messageInfo_StopJobReq.Size(m)
}
func (m *StopJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StopJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_StopJobReq proto.InternalMessageInfo

func (m *StopJobReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StopJobRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopJobRes) Reset()         { *m = StopJobRes{} }
func (m *StopJobRes) String() string { return proto.CompactTextString(m) }
func (*StopJobRes) ProtoMessage()    {}
func (*StopJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{5}
}

func (m *StopJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopJobRes.Unmarshal(m, b)
}
func (m *StopJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopJobRes.Marshal(b, m, deterministic)
}
func (m *StopJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopJobRes.Merge(m, src)
}
func (m *StopJobRes) XXX_Size() int {
	return xxx_messageInfo_StopJobRes.Size(m)
}
func (m *StopJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StopJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_StopJobRes proto.InternalMessageInfo

func (m *StopJobRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DoneScraperReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoneScraperReq) Reset()         { *m = DoneScraperReq{} }
func (m *DoneScraperReq) String() string { return proto.CompactTextString(m) }
func (*DoneScraperReq) ProtoMessage()    {}
func (*DoneScraperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{6}
}

func (m *DoneScraperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoneScraperReq.Unmarshal(m, b)
}
func (m *DoneScraperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoneScraperReq.Marshal(b, m, deterministic)
}
func (m *DoneScraperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoneScraperReq.Merge(m, src)
}
func (m *DoneScraperReq) XXX_Size() int {
	return xxx_messageInfo_DoneScraperReq.Size(m)
}
func (m *DoneScraperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DoneScraperReq.DiscardUnknown(m)
}

var xxx_messageInfo_DoneScraperReq proto.InternalMessageInfo

func (m *DoneScraperReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DoneScraperRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoneScraperRes) Reset()         { *m = DoneScraperRes{} }
func (m *DoneScraperRes) String() string { return proto.CompactTextString(m) }
func (*DoneScraperRes) ProtoMessage()    {}
func (*DoneScraperRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{7}
}

func (m *DoneScraperRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoneScraperRes.Unmarshal(m, b)
}
func (m *DoneScraperRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoneScraperRes.Marshal(b, m, deterministic)
}
func (m *DoneScraperRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoneScraperRes.Merge(m, src)
}
func (m *DoneScraperRes) XXX_Size() int {
	return xxx_messageInfo_DoneScraperRes.Size(m)
}
func (m *DoneScraperRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DoneScraperRes.DiscardUnknown(m)
}

var xxx_messageInfo_DoneScraperRes proto.InternalMessageInfo

func (m *DoneScraperRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DoneAnalyzerReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoneAnalyzerReq) Reset()         { *m = DoneAnalyzerReq{} }
func (m *DoneAnalyzerReq) String() string { return proto.CompactTextString(m) }
func (*DoneAnalyzerReq) ProtoMessage()    {}
func (*DoneAnalyzerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{8}
}

func (m *DoneAnalyzerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoneAnalyzerReq.Unmarshal(m, b)
}
func (m *DoneAnalyzerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoneAnalyzerReq.Marshal(b, m, deterministic)
}
func (m *DoneAnalyzerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoneAnalyzerReq.Merge(m, src)
}
func (m *DoneAnalyzerReq) XXX_Size() int {
	return xxx_messageInfo_DoneAnalyzerReq.Size(m)
}
func (m *DoneAnalyzerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DoneAnalyzerReq.DiscardUnknown(m)
}

var xxx_messageInfo_DoneAnalyzerReq proto.InternalMessageInfo

func (m *DoneAnalyzerReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DoneAnalyzerRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoneAnalyzerRes) Reset()         { *m = DoneAnalyzerRes{} }
func (m *DoneAnalyzerRes) String() string { return proto.CompactTextString(m) }
func (*DoneAnalyzerRes) ProtoMessage()    {}
func (*DoneAnalyzerRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{9}
}

func (m *DoneAnalyzerRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoneAnalyzerRes.Unmarshal(m, b)
}
func (m *DoneAnalyzerRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoneAnalyzerRes.Marshal(b, m, deterministic)
}
func (m *DoneAnalyzerRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoneAnalyzerRes.Merge(m, src)
}
func (m *DoneAnalyzerRes) XXX_Size() int {
	return xxx_messageInfo_DoneAnalyzerRes.Size(m)
}
func (m *DoneAnalyzerRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DoneAnalyzerRes.DiscardUnknown(m)
}

var xxx_messageInfo_DoneAnalyzerRes proto.InternalMessageInfo

func (m *DoneAnalyzerRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type UpdateJobStatusReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobStatusReq) Reset()         { *m = UpdateJobStatusReq{} }
func (m *UpdateJobStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateJobStatusReq) ProtoMessage()    {}
func (*UpdateJobStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{10}
}

func (m *UpdateJobStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobStatusReq.Unmarshal(m, b)
}
func (m *UpdateJobStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateJobStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobStatusReq.Merge(m, src)
}
func (m *UpdateJobStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateJobStatusReq.Size(m)
}
func (m *UpdateJobStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobStatusReq proto.InternalMessageInfo

func (m *UpdateJobStatusReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateJobStatusReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpdateJobStatusRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobStatusRes) Reset()         { *m = UpdateJobStatusRes{} }
func (m *UpdateJobStatusRes) String() string { return proto.CompactTextString(m) }
func (*UpdateJobStatusRes) ProtoMessage()    {}
func (*UpdateJobStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{11}
}

func (m *UpdateJobStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobStatusRes.Unmarshal(m, b)
}
func (m *UpdateJobStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobStatusRes.Marshal(b, m, deterministic)
}
func (m *UpdateJobStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobStatusRes.Merge(m, src)
}
func (m *UpdateJobStatusRes) XXX_Size() int {
	return xxx_messageInfo_UpdateJobStatusRes.Size(m)
}
func (m *UpdateJobStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobStatusRes proto.InternalMessageInfo

func (m *UpdateJobStatusRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetJobListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobListReq) Reset()         { *m = GetJobListReq{} }
func (m *GetJobListReq) String() string { return proto.CompactTextString(m) }
func (*GetJobListReq) ProtoMessage()    {}
func (*GetJobListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{12}
}

func (m *GetJobListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobListReq.Unmarshal(m, b)
}
func (m *GetJobListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobListReq.Marshal(b, m, deterministic)
}
func (m *GetJobListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobListReq.Merge(m, src)
}
func (m *GetJobListReq) XXX_Size() int {
	return xxx_messageInfo_GetJobListReq.Size(m)
}
func (m *GetJobListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobListReq proto.InternalMessageInfo

type GetJobListRes struct {
	Job                  []*job.Job `protobuf:"bytes,1,rep,name=Job,proto3" json:"Job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetJobListRes) Reset()         { *m = GetJobListRes{} }
func (m *GetJobListRes) String() string { return proto.CompactTextString(m) }
func (*GetJobListRes) ProtoMessage()    {}
func (*GetJobListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{13}
}

func (m *GetJobListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobListRes.Unmarshal(m, b)
}
func (m *GetJobListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobListRes.Marshal(b, m, deterministic)
}
func (m *GetJobListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobListRes.Merge(m, src)
}
func (m *GetJobListRes) XXX_Size() int {
	return xxx_messageInfo_GetJobListRes.Size(m)
}
func (m *GetJobListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobListRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobListRes proto.InternalMessageInfo

func (m *GetJobListRes) GetJob() []*job.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type GetWorkerListReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkerListReq) Reset()         { *m = GetWorkerListReq{} }
func (m *GetWorkerListReq) String() string { return proto.CompactTextString(m) }
func (*GetWorkerListReq) ProtoMessage()    {}
func (*GetWorkerListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{14}
}

func (m *GetWorkerListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkerListReq.Unmarshal(m, b)
}
func (m *GetWorkerListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkerListReq.Marshal(b, m, deterministic)
}
func (m *GetWorkerListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkerListReq.Merge(m, src)
}
func (m *GetWorkerListReq) XXX_Size() int {
	return xxx_messageInfo_GetWorkerListReq.Size(m)
}
func (m *GetWorkerListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkerListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkerListReq proto.InternalMessageInfo

func (m *GetWorkerListReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetWorkerListRes struct {
	Worker               []*worker.Worker `protobuf:"bytes,1,rep,name=Worker,proto3" json:"Worker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetWorkerListRes) Reset()         { *m = GetWorkerListRes{} }
func (m *GetWorkerListRes) String() string { return proto.CompactTextString(m) }
func (*GetWorkerListRes) ProtoMessage()    {}
func (*GetWorkerListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f0dfd118c1b1e1, []int{15}
}

func (m *GetWorkerListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkerListRes.Unmarshal(m, b)
}
func (m *GetWorkerListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkerListRes.Marshal(b, m, deterministic)
}
func (m *GetWorkerListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkerListRes.Merge(m, src)
}
func (m *GetWorkerListRes) XXX_Size() int {
	return xxx_messageInfo_GetWorkerListRes.Size(m)
}
func (m *GetWorkerListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkerListRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkerListRes proto.InternalMessageInfo

func (m *GetWorkerListRes) GetWorker() []*worker.Worker {
	if m != nil {
		return m.Worker
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateNewJobReq)(nil), "pb.svc.manager.CreateNewJobReq")
	proto.RegisterType((*CreateNewJobRes)(nil), "pb.svc.manager.CreateNewJobRes")
	proto.RegisterType((*GetJobStatusReq)(nil), "pb.svc.manager.GetJobStatusReq")
	proto.RegisterType((*GetJobStatusRes)(nil), "pb.svc.manager.GetJobStatusRes")
	proto.RegisterType((*StopJobReq)(nil), "pb.svc.manager.StopJobReq")
	proto.RegisterType((*StopJobRes)(nil), "pb.svc.manager.StopJobRes")
	proto.RegisterType((*DoneScraperReq)(nil), "pb.svc.manager.DoneScraperReq")
	proto.RegisterType((*DoneScraperRes)(nil), "pb.svc.manager.DoneScraperRes")
	proto.RegisterType((*DoneAnalyzerReq)(nil), "pb.svc.manager.DoneAnalyzerReq")
	proto.RegisterType((*DoneAnalyzerRes)(nil), "pb.svc.manager.DoneAnalyzerRes")
	proto.RegisterType((*UpdateJobStatusReq)(nil), "pb.svc.manager.UpdateJobStatusReq")
	proto.RegisterType((*UpdateJobStatusRes)(nil), "pb.svc.manager.UpdateJobStatusRes")
	proto.RegisterType((*GetJobListReq)(nil), "pb.svc.manager.GetJobListReq")
	proto.RegisterType((*GetJobListRes)(nil), "pb.svc.manager.GetJobListRes")
	proto.RegisterType((*GetWorkerListReq)(nil), "pb.svc.manager.GetWorkerListReq")
	proto.RegisterType((*GetWorkerListRes)(nil), "pb.svc.manager.GetWorkerListRes")
}

func init() { proto.RegisterFile("pb/svc/manager/manager.proto", fileDescriptor_75f0dfd118c1b1e1) }

var fileDescriptor_75f0dfd118c1b1e1 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xd6, 0x3a, 0xad, 0x85, 0x1b, 0xb4, 0x93, 0x05, 0x53, 0x65, 0x06, 0x14, 0x8b, 0x87, 0x4d,
	0x02, 0x67, 0x3f, 0x1e, 0x78, 0xe1, 0xa5, 0x03, 0x69, 0x5a, 0xc5, 0x10, 0x6a, 0x85, 0x10, 0x48,
	0x3c, 0xc4, 0x8d, 0x55, 0xb2, 0x76, 0x75, 0x66, 0xbb, 0xab, 0xc6, 0xff, 0xc0, 0xff, 0x8c, 0x62,
	0xbb, 0x6b, 0xe2, 0x24, 0xcd, 0x43, 0x15, 0xdd, 0xdd, 0x77, 0x9f, 0xad, 0xcf, 0xdf, 0x5d, 0xe1,
	0x20, 0x61, 0x81, 0xba, 0x1b, 0x07, 0x37, 0xe1, 0x3c, 0x9c, 0x70, 0xb9, 0xfa, 0xd2, 0x44, 0x0a,
	0x2d, 0x50, 0x3b, 0x61, 0x54, 0xdd, 0x8d, 0xa9, 0xcb, 0xe2, 0xe7, 0x09, 0x0b, 0x16, 0xf3, 0x58,
	0x07, 0xd7, 0x82, 0xa5, 0x3f, 0x0b, 0xc3, 0x2f, 0x56, 0xe9, 0xa5, 0x90, 0x53, 0x2e, 0xdd, 0xc7,
	0x16, 0x49, 0x1f, 0x3a, 0x9f, 0x24, 0x0f, 0x35, 0xff, 0xca, 0x97, 0x03, 0xc1, 0x86, 0xfc, 0x16,
	0x75, 0xa1, 0x35, 0xe5, 0xf7, 0x4b, 0x21, 0xa3, 0xee, 0x56, 0x6f, 0xeb, 0xf0, 0xf1, 0x70, 0x15,
	0xa2, 0x67, 0xb0, 0x23, 0x96, 0x73, 0x2e, 0xbb, 0x0d, 0x93, 0xb7, 0x01, 0xf9, 0xed, 0x53, 0xa8,
	0x3c, 0xc5, 0x76, 0x96, 0x02, 0xc3, 0x23, 0x7b, 0xfe, 0x65, 0xd4, 0x6d, 0x98, 0xd2, 0x43, 0x9c,
	0xd2, 0x5f, 0x0b, 0x76, 0x19, 0x75, 0xb7, 0x2d, 0xbd, 0x09, 0xc8, 0x07, 0xe8, 0x5c, 0x70, 0x3d,
	0x10, 0x6c, 0xa4, 0x43, 0xbd, 0x50, 0xe9, 0x0d, 0xdb, 0xd0, 0x88, 0x57, 0x97, 0x6b, 0xc4, 0x55,
	0xf7, 0x3a, 0xf2, 0x1b, 0x15, 0xda, 0x87, 0xa6, 0x32, 0x81, 0x6b, 0x76, 0x11, 0x39, 0x00, 0x18,
	0x69, 0x91, 0x38, 0x01, 0x3c, 0x7a, 0xf2, 0x36, 0x53, 0x35, 0x1c, 0x92, 0xab, 0xc5, 0x4c, 0xaf,
	0x38, 0x6c, 0x44, 0x7a, 0xd0, 0xfe, 0x2c, 0xe6, 0x7c, 0x34, 0x96, 0x61, 0xc2, 0x65, 0x19, 0xcf,
	0xa1, 0x87, 0xa8, 0xe6, 0x7a, 0x03, 0x9d, 0x14, 0xd9, 0x9f, 0x87, 0xb3, 0xfb, 0xbf, 0xe5, 0x64,
	0x47, 0x3e, 0xa4, 0x9a, 0xed, 0x23, 0xa0, 0xef, 0x49, 0x14, 0x6a, 0xbe, 0x51, 0xc4, 0xb5, 0x36,
	0x8d, 0x9c, 0x36, 0xef, 0x4a, 0xba, 0xab, 0xcf, 0xea, 0xc0, 0x53, 0x2b, 0xfa, 0x97, 0x58, 0xe9,
	0x21, 0xbf, 0x25, 0x67, 0xf9, 0x84, 0x42, 0x04, 0xb6, 0x07, 0x82, 0x19, 0x5f, 0xec, 0x9e, 0xee,
	0xd1, 0x84, 0xd1, 0xd4, 0x9c, 0x34, 0xf5, 0x6b, 0xaa, 0x70, 0x5a, 0x24, 0x04, 0xf6, 0x2e, 0xb8,
	0xfe, 0x61, 0x8c, 0xe1, 0x88, 0x0a, 0x02, 0x9c, 0x17, 0x30, 0x0a, 0x51, 0x68, 0xda, 0x84, 0xa3,
	0xdf, 0x7f, 0xa0, 0x77, 0xa6, 0xb7, 0xd5, 0xa1, 0x43, 0x9d, 0xfe, 0xdb, 0x81, 0xd6, 0x95, 0x9d,
	0x1e, 0xf4, 0x0d, 0x9e, 0x64, 0x6d, 0x8c, 0x5e, 0xd3, 0xfc, 0x78, 0x51, 0x6f, 0x4e, 0x70, 0x0d,
	0x40, 0xa5, 0x8c, 0x59, 0x03, 0x16, 0x19, 0x3d, 0x5f, 0xe3, 0x1a, 0x80, 0x42, 0x03, 0x80, 0xb5,
	0x98, 0xe8, 0x65, 0x39, 0xdc, 0x09, 0x86, 0x37, 0x96, 0x15, 0x1a, 0x99, 0x87, 0x59, 0xeb, 0x87,
	0x7a, 0x25, 0xf8, 0xdc, 0x13, 0xe0, 0x3a, 0x84, 0x42, 0x3f, 0xa1, 0xe3, 0x99, 0x05, 0x11, 0xbf,
	0xa9, 0xe8, 0x45, 0x5c, 0x8f, 0x51, 0xe8, 0x0a, 0x76, 0x33, 0xd3, 0x83, 0x5e, 0xf9, 0x2d, 0xf9,
	0xe1, 0xc3, 0x9b, 0xeb, 0xe6, 0x71, 0xb2, 0xf3, 0x53, 0x7c, 0x1c, 0x6f, 0x00, 0x71, 0x0d, 0x40,
	0xa1, 0x3e, 0xb4, 0xdc, 0x9a, 0x40, 0xd8, 0xc7, 0xae, 0xb7, 0x0b, 0xae, 0xae, 0xa9, 0xf3, 0x93,
	0x5f, 0xc1, 0x24, 0xd6, 0x7f, 0x16, 0x8c, 0x8e, 0xc5, 0x4d, 0x10, 0x4e, 0x66, 0x71, 0xc4, 0x4f,
	0x8e, 0x8f, 0x83, 0x28, 0x9c, 0xbe, 0x77, 0x1b, 0x34, 0xc8, 0xff, 0x25, 0xb0, 0xa6, 0xd9, 0xe3,
	0x67, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xbf, 0x78, 0x96, 0x2b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
	CreateNewJob(ctx context.Context, in *CreateNewJobReq, opts ...grpc.CallOption) (*CreateNewJobRes, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusReq, opts ...grpc.CallOption) (*GetJobStatusRes, error)
	GetJobList(ctx context.Context, in *GetJobListReq, opts ...grpc.CallOption) (*GetJobListRes, error)
	GetWorkerList(ctx context.Context, in *GetWorkerListReq, opts ...grpc.CallOption) (*GetWorkerListRes, error)
	UpdateJobStatus(ctx context.Context, in *UpdateJobStatusReq, opts ...grpc.CallOption) (*UpdateJobStatusRes, error)
	DoneScraper(ctx context.Context, in *DoneScraperReq, opts ...grpc.CallOption) (*DoneScraperRes, error)
	DoneAnalyzer(ctx context.Context, in *DoneAnalyzerReq, opts ...grpc.CallOption) (*DoneAnalyzerRes, error)
	StopJob(ctx context.Context, in *StopJobReq, opts ...grpc.CallOption) (*StopJobRes, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) CreateNewJob(ctx context.Context, in *CreateNewJobReq, opts ...grpc.CallOption) (*CreateNewJobRes, error) {
	out := new(CreateNewJobRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.Manager/CreateNewJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetJobStatus(ctx context.Context, in *GetJobStatusReq, opts ...grpc.CallOption) (*GetJobStatusRes, error) {
	out := new(GetJobStatusRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.Manager/GetJobStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetJobList(ctx context.Context, in *GetJobListReq, opts ...grpc.CallOption) (*GetJobListRes, error) {
	out := new(GetJobListRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.Manager/GetJobList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetWorkerList(ctx context.Context, in *GetWorkerListReq, opts ...grpc.CallOption) (*GetWorkerListRes, error) {
	out := new(GetWorkerListRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.Manager/GetWorkerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) UpdateJobStatus(ctx context.Context, in *UpdateJobStatusReq, opts ...grpc.CallOption) (*UpdateJobStatusRes, error) {
	out := new(UpdateJobStatusRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.Manager/UpdateJobStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DoneScraper(ctx context.Context, in *DoneScraperReq, opts ...grpc.CallOption) (*DoneScraperRes, error) {
	out := new(DoneScraperRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.Manager/DoneScraper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DoneAnalyzer(ctx context.Context, in *DoneAnalyzerReq, opts ...grpc.CallOption) (*DoneAnalyzerRes, error) {
	out := new(DoneAnalyzerRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.Manager/DoneAnalyzer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) StopJob(ctx context.Context, in *StopJobReq, opts ...grpc.CallOption) (*StopJobRes, error) {
	out := new(StopJobRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.Manager/StopJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
	CreateNewJob(context.Context, *CreateNewJobReq) (*CreateNewJobRes, error)
	GetJobStatus(context.Context, *GetJobStatusReq) (*GetJobStatusRes, error)
	GetJobList(context.Context, *GetJobListReq) (*GetJobListRes, error)
	GetWorkerList(context.Context, *GetWorkerListReq) (*GetWorkerListRes, error)
	UpdateJobStatus(context.Context, *UpdateJobStatusReq) (*UpdateJobStatusRes, error)
	DoneScraper(context.Context, *DoneScraperReq) (*DoneScraperRes, error)
	DoneAnalyzer(context.Context, *DoneAnalyzerReq) (*DoneAnalyzerRes, error)
	StopJob(context.Context, *StopJobReq) (*StopJobRes, error)
}

// UnimplementedManagerServer can be embedded to have forward compatible implementations.
type UnimplementedManagerServer struct {
}

func (*UnimplementedManagerServer) CreateNewJob(ctx context.Context, req *CreateNewJobReq) (*CreateNewJobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewJob not implemented")
}
func (*UnimplementedManagerServer) GetJobStatus(ctx context.Context, req *GetJobStatusReq) (*GetJobStatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (*UnimplementedManagerServer) GetJobList(ctx context.Context, req *GetJobListReq) (*GetJobListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobList not implemented")
}
func (*UnimplementedManagerServer) GetWorkerList(ctx context.Context, req *GetWorkerListReq) (*GetWorkerListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkerList not implemented")
}
func (*UnimplementedManagerServer) UpdateJobStatus(ctx context.Context, req *UpdateJobStatusReq) (*UpdateJobStatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobStatus not implemented")
}
func (*UnimplementedManagerServer) DoneScraper(ctx context.Context, req *DoneScraperReq) (*DoneScraperRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoneScraper not implemented")
}
func (*UnimplementedManagerServer) DoneAnalyzer(ctx context.Context, req *DoneAnalyzerReq) (*DoneAnalyzerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoneAnalyzer not implemented")
}
func (*UnimplementedManagerServer) StopJob(ctx context.Context, req *StopJobReq) (*StopJobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopJob not implemented")
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_CreateNewJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).CreateNewJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.Manager/CreateNewJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).CreateNewJob(ctx, req.(*CreateNewJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.Manager/GetJobStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetJobStatus(ctx, req.(*GetJobStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetJobList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetJobList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.Manager/GetJobList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetJobList(ctx, req.(*GetJobListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetWorkerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetWorkerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.Manager/GetWorkerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetWorkerList(ctx, req.(*GetWorkerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_UpdateJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).UpdateJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.Manager/UpdateJobStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).UpdateJobStatus(ctx, req.(*UpdateJobStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DoneScraper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoneScraperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DoneScraper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.Manager/DoneScraper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DoneScraper(ctx, req.(*DoneScraperReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DoneAnalyzer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoneAnalyzerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DoneAnalyzer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.Manager/DoneAnalyzer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DoneAnalyzer(ctx, req.(*DoneAnalyzerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.Manager/StopJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).StopJob(ctx, req.(*StopJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.svc.manager.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewJob",
			Handler:    _Manager_CreateNewJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _Manager_GetJobStatus_Handler,
		},
		{
			MethodName: "GetJobList",
			Handler:    _Manager_GetJobList_Handler,
		},
		{
			MethodName: "GetWorkerList",
			Handler:    _Manager_GetWorkerList_Handler,
		},
		{
			MethodName: "UpdateJobStatus",
			Handler:    _Manager_UpdateJobStatus_Handler,
		},
		{
			MethodName: "DoneScraper",
			Handler:    _Manager_DoneScraper_Handler,
		},
		{
			MethodName: "DoneAnalyzer",
			Handler:    _Manager_DoneAnalyzer_Handler,
		},
		{
			MethodName: "StopJob",
			Handler:    _Manager_StopJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/svc/manager/manager.proto",
}
