version: "3.5"
x-services-volume: &services-volume
    type: bind

services:
    envoy:
        build:
            context: ./
            dockerfile: ./net/grpc/gateway/docker/envoy/Dockerfile
        image: grpcweb/envoy
        ports:
            - "8080:8080"
        links:
            - node-server
