version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  # apid:
  #   container_name: apid
  #   image: ghcr.io/aglide100/dak-keyword-apid:latest
  #   ports:
  #     - 50011:50011
  #     - 50010:50010
      
  # provisioned:
  #   container_name: provisioned
  #   image: ghcr.io/aglide100/dak-keyword-provisioned:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 50012:50012

  db:
    container_name: db
    build: 
      context: ./
      dockerfile: ./cmd/db/Dockerfile
    # image: ghcr.io/aglide100/dak-keyword-db:latest
    volumes:
      - <<: *services-volume
        # source: ${HOST}/postgres
        source: /tmp/dak-keyword
        target: /var/lib/postgres
    ports:
      #- 5432:5432
      - 8342:5432
    hostname: postgres
    networks:
      - dak_keyword_network
    environment:
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${DB_NAME}
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

networks:
  dak_keyword_network:
    driver: bridge
    ipam:
      driver: default
