version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  postgres:
    container_name: postgres
    build:
      context: ./cmd/db
    volumes:
      - <<: *services-volume
        # source: ${HOST}/postgres
        source: /tmp/dak-keyword
        target: /var/lib/postgres
    ports:
      - 5432:5432
      # - 8342:8342
    hostname: postgres
    networks:
      - dak_keyword_network
    environment:
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${DB_NAME}
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

networks:
  dak_keyword_network:
    driver: bridge
    ipam:
      driver: default
