version: "3.5"
x-services-volume: &services-volume
    type: bind

services:
    db:
        image: ghcr.io/aglide100/dak-keyword-db:latest
        # image: db
        # volumes:
        #   - <<: *services-volume
        #     # source: ${HOST}/postgres
        #     source: /tmp/dak-keyword
        #     target: /var/lib/postgres
        env_file:
            - ./env/db.env
        # ports:
        #     - 5432:5432
        networks:
            - keyword-network
        deploy:
            placement:
                constraints: [node.role==manager]
    apid:
        image: ghcr.io/aglide100/dak-keyword-apid:latest
        # image: apid
        env_file:
            - ./env/dbConfig.env
            - ./env/tweet_secret.env
        networks:
            - keyword-network
            - traefik-network
        secrets:
            - crt-file
            - key-file
        ports:
            - 50011:50011
            - 50010:50010
        environment:
            - TLS=true
        depends_on:
            - db
        deploy:
            placement:
                constraints: [node.role==manager]
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-network
                - traefik.http.routers.keyword-apid.rule=Host(`keyword-grpc.${DOMAIN}`)
                #- traefik.http.routers.keyword-apid.middlewares=redirect-to-https
                - traefik.http.routers.keyword-apid.entrypoints=web
                - traefik.http.services.keyword-apid.loadbalancer.server.port=50011
                - traefik.http.routers.keyword-apid--https.rule=Host(`keyword-grpc.${DOMAIN}`)
                # - traefik.http.routers.keyword-apid--https.tls=true
                # - traefik.http.routers.keyword-apid--https.tls.certresolver=myresolver
                - traefik.http.routers.keyword-apid--https.entrypoints=websecure

    provisioned:
        image: ghcr.io/aglide100/dak-keyword-provisioned:latest
        # image: provisioned
        env_file:
            - ./env/dbConfig.env
        networks:
            - keyword-network
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        # ports:
        #     - 50012:50012
        depends_on:
            - db
        deploy:
            placement:
                constraints: [node.role==manager]

    ui:
        image: ghcr.io/aglide100/dak-keyword-ui:latest
        # image: node
        ports:
            - 3000:3000
        networks:
            - keyword-network
            - traefik-network
        environment:
            - GRPCWEBADDR=keyword-grpc.${DOMAIN}
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-network
                - traefik.http.routers.keyword-node.rule=Host(`keyword.${DOMAIN}`)
                - traefik.http.routers.keyword-node.middlewares=redirect-to-https
                - traefik.http.routers.keyword-node.entrypoints=web
                - traefik.http.services.keyword-node.loadbalancer.server.port=3000
                - traefik.http.routers.keyword-node--https.rule=Host(`keyword.${DOMAIN}`)
                - traefik.http.routers.keyword-node--https.tls=true
                - traefik.http.routers.keyword-node--https.tls.certresolver=myresolver
                - traefik.http.routers.keyword-node--https.entrypoints=websecure

    # viz:
    #     image: dockersamples/visualizer
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     networks:
    #         - keyword-network
    #     ports:
    #         - 1999:8080

secrets:
    crt-file:
        file: ./keys/localhost.crt
    key-file:
        file: ./keys/localhost.key
    # crt-file:
    #     file: ./keys/server.crt
    # key-file:
    #     file: ./keys/server.key

networks:
    keyword-network:
        driver: overlay
    traefik-network:
        external: true

volumes:
    keys:
        external:
            name: keys
