# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/unit/similarity/similarity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#pb/unit/similarity/similarity.proto\x12\x12pb.unit.similarity\"\x0c\n\nSimilarityB5Z3github.com/aglide100/dak-keyword/pb/unit/similarityb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.unit.similarity.similarity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/aglide100/dak-keyword/pb/unit/similarity'
  _SIMILARITY._serialized_start=59
  _SIMILARITY._serialized_end=71
# @@protoc_insertion_point(module_scope)
