# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/svc/analyzer/analyzer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1epb/svc/analyzer/analyzer.proto\x12\x0fpb.svc.analyzer\"\x12\n\x10StartAnalyzerReq\"\x12\n\x10StartAnalyzerRes\"\x0e\n\x0cGetStatusReq\".\n\x0cGetStatusRes\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x05\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xac\x01\n\x08\x41nalyzer\x12U\n\rStartAnalyzer\x12!.pb.svc.analyzer.StartAnalyzerReq\x1a!.pb.svc.analyzer.StartAnalyzerRes\x12I\n\tGetStatus\x12\x1d.pb.svc.analyzer.GetStatusReq\x1a\x1d.pb.svc.analyzer.GetStatusResB2Z0github.com/aglide100/dak-keyword/pb/svc/analyzerb\x06proto3')



_STARTANALYZERREQ = DESCRIPTOR.message_types_by_name['StartAnalyzerReq']
_STARTANALYZERRES = DESCRIPTOR.message_types_by_name['StartAnalyzerRes']
_GETSTATUSREQ = DESCRIPTOR.message_types_by_name['GetStatusReq']
_GETSTATUSRES = DESCRIPTOR.message_types_by_name['GetStatusRes']
StartAnalyzerReq = _reflection.GeneratedProtocolMessageType('StartAnalyzerReq', (_message.Message,), {
  'DESCRIPTOR' : _STARTANALYZERREQ,
  '__module__' : 'pb.svc.analyzer.analyzer_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.analyzer.StartAnalyzerReq)
  })
_sym_db.RegisterMessage(StartAnalyzerReq)

StartAnalyzerRes = _reflection.GeneratedProtocolMessageType('StartAnalyzerRes', (_message.Message,), {
  'DESCRIPTOR' : _STARTANALYZERRES,
  '__module__' : 'pb.svc.analyzer.analyzer_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.analyzer.StartAnalyzerRes)
  })
_sym_db.RegisterMessage(StartAnalyzerRes)

GetStatusReq = _reflection.GeneratedProtocolMessageType('GetStatusReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATUSREQ,
  '__module__' : 'pb.svc.analyzer.analyzer_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.analyzer.GetStatusReq)
  })
_sym_db.RegisterMessage(GetStatusReq)

GetStatusRes = _reflection.GeneratedProtocolMessageType('GetStatusRes', (_message.Message,), {
  'DESCRIPTOR' : _GETSTATUSRES,
  '__module__' : 'pb.svc.analyzer.analyzer_pb2'
  # @@protoc_insertion_point(class_scope:pb.svc.analyzer.GetStatusRes)
  })
_sym_db.RegisterMessage(GetStatusRes)

_ANALYZER = DESCRIPTOR.services_by_name['Analyzer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/aglide100/dak-keyword/pb/svc/analyzer'
  _STARTANALYZERREQ._serialized_start=51
  _STARTANALYZERREQ._serialized_end=69
  _STARTANALYZERRES._serialized_start=71
  _STARTANALYZERRES._serialized_end=89
  _GETSTATUSREQ._serialized_start=91
  _GETSTATUSREQ._serialized_end=105
  _GETSTATUSRES._serialized_start=107
  _GETSTATUSRES._serialized_end=153
  _ANALYZER._serialized_start=156
  _ANALYZER._serialized_end=328
# @@protoc_insertion_point(module_scope)
