version: "3.5"
# x-services-volume: &services-volume
#   type: bind

services:
    py:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: Analyzer.py
        hostname: py
        networks:
            - db_keyword-network
        environment:
            DB_ADDR: db
            DB_NAME: keyword
            DB_USER: table_admin
            DB_PASSWORD: HelloWorld
            DB_PORT: 5432
            WORKER_ID: test

networks:
    db_keyword-network:
        external: true
