version: "3.5"
# x-services-volume: &services-volume
#   type: bind

services:
    py1:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: Analyzer.py
        hostname: py
        networks:
            - db_keyword-network
        environment:
            DB_ADDR: db
            DB_NAME: keyword
            DB_USER: table_admin
            DB_PASSWORD: HelloWorld
            # DB_PORT: 5432
            DB_PORT: 8432
            WORKER_ID: ab402684-9a33-4583-9d50-a48e8f1aabca

networks:
    db_keyword-network:
        external: true
