// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: pb/svc/manager/scraper.proto

package scraper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhenDoneScraperReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	JobId    string `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
}

func (x *WhenDoneScraperReq) Reset() {
	*x = WhenDoneScraperReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_manager_scraper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhenDoneScraperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhenDoneScraperReq) ProtoMessage() {}

func (x *WhenDoneScraperReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_manager_scraper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhenDoneScraperReq.ProtoReflect.Descriptor instead.
func (*WhenDoneScraperReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_manager_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *WhenDoneScraperReq) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WhenDoneScraperReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WhenDoneScraperRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *WhenDoneScraperRes) Reset() {
	*x = WhenDoneScraperRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_manager_scraper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhenDoneScraperRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhenDoneScraperRes) ProtoMessage() {}

func (x *WhenDoneScraperRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_manager_scraper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhenDoneScraperRes.ProtoReflect.Descriptor instead.
func (*WhenDoneScraperRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_manager_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *WhenDoneScraperRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type WhenStartScraperReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WhenStartScraperReq) Reset() {
	*x = WhenStartScraperReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_manager_scraper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhenStartScraperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhenStartScraperReq) ProtoMessage() {}

func (x *WhenStartScraperReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_manager_scraper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhenStartScraperReq.ProtoReflect.Descriptor instead.
func (*WhenStartScraperReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_manager_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *WhenStartScraperReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WhenStartScraperRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *WhenStartScraperRes) Reset() {
	*x = WhenStartScraperRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_manager_scraper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhenStartScraperRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhenStartScraperRes) ProtoMessage() {}

func (x *WhenStartScraperRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_manager_scraper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhenStartScraperRes.ProtoReflect.Descriptor instead.
func (*WhenStartScraperRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_manager_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *WhenStartScraperRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type WhenScraperHavingErrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *WhenScraperHavingErrReq) Reset() {
	*x = WhenScraperHavingErrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_manager_scraper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhenScraperHavingErrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhenScraperHavingErrReq) ProtoMessage() {}

func (x *WhenScraperHavingErrReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_manager_scraper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhenScraperHavingErrReq.ProtoReflect.Descriptor instead.
func (*WhenScraperHavingErrReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_manager_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *WhenScraperHavingErrReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WhenScraperHavingErrReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type WhenScraperHavingErrRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhenScraperHavingErrRes) Reset() {
	*x = WhenScraperHavingErrRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_manager_scraper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhenScraperHavingErrRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhenScraperHavingErrRes) ProtoMessage() {}

func (x *WhenScraperHavingErrRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_manager_scraper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhenScraperHavingErrRes.ProtoReflect.Descriptor instead.
func (*WhenScraperHavingErrRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_manager_scraper_proto_rawDescGZIP(), []int{5}
}

type WhenScraperHavingMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *WhenScraperHavingMsgReq) Reset() {
	*x = WhenScraperHavingMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_manager_scraper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhenScraperHavingMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhenScraperHavingMsgReq) ProtoMessage() {}

func (x *WhenScraperHavingMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_manager_scraper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhenScraperHavingMsgReq.ProtoReflect.Descriptor instead.
func (*WhenScraperHavingMsgReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_manager_scraper_proto_rawDescGZIP(), []int{6}
}

func (x *WhenScraperHavingMsgReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WhenScraperHavingMsgReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type WhenScraperHavingMsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhenScraperHavingMsgRes) Reset() {
	*x = WhenScraperHavingMsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_manager_scraper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhenScraperHavingMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhenScraperHavingMsgRes) ProtoMessage() {}

func (x *WhenScraperHavingMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_manager_scraper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhenScraperHavingMsgRes.ProtoReflect.Descriptor instead.
func (*WhenScraperHavingMsgRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_manager_scraper_proto_rawDescGZIP(), []int{7}
}

var File_pb_svc_manager_scraper_proto protoreflect.FileDescriptor

var file_pb_svc_manager_scraper_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x73,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x22, 0x46, 0x0a, 0x12, 0x57, 0x68, 0x65, 0x6e, 0x44, 0x6f,
	0x6e, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x2c,
	0x0a, 0x12, 0x57, 0x68, 0x65, 0x6e, 0x44, 0x6f, 0x6e, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x25, 0x0a, 0x13,
	0x57, 0x68, 0x65, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x57, 0x68, 0x65, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x3b, 0x0a, 0x17, 0x57, 0x68, 0x65, 0x6e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65,
	0x72, 0x48, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x45, 0x72, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x19, 0x0a, 0x17, 0x57, 0x68, 0x65, 0x6e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x48, 0x61,
	0x76, 0x69, 0x6e, 0x67, 0x45, 0x72, 0x72, 0x52, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x17, 0x57, 0x68,
	0x65, 0x6e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x48, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x19, 0x0a, 0x17, 0x57, 0x68, 0x65, 0x6e, 0x53,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x48, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x32, 0xdd, 0x03, 0x0a, 0x0e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6c, 0x0a, 0x10, 0x57, 0x68, 0x65, 0x6e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x70, 0x62, 0x2e, 0x73,
	0x76, 0x63, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70,
	0x65, 0x72, 0x2e, 0x57, 0x68, 0x65, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x63, 0x72, 0x61,
	0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e,
	0x57, 0x68, 0x65, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x12, 0x69, 0x0a, 0x0f, 0x57, 0x68, 0x65, 0x6e, 0x44, 0x6f, 0x6e, 0x65, 0x53,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x12, 0x2a, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e,
	0x57, 0x68, 0x65, 0x6e, 0x44, 0x6f, 0x6e, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x2a, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x57, 0x68, 0x65, 0x6e,
	0x44, 0x6f, 0x6e, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x78,
	0x0a, 0x14, 0x57, 0x68, 0x65, 0x6e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x48, 0x61, 0x76,
	0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x12, 0x2f, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e,
	0x57, 0x68, 0x65, 0x6e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x48, 0x61, 0x76, 0x69, 0x6e,
	0x67, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x2f, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72,
	0x2e, 0x57, 0x68, 0x65, 0x6e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x48, 0x61, 0x76, 0x69,
	0x6e, 0x67, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x12, 0x78, 0x0a, 0x14, 0x57, 0x68, 0x65, 0x6e,
	0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x48, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x45, 0x72, 0x72,
	0x12, 0x2f, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x57, 0x68, 0x65, 0x6e, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x72, 0x48, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x45, 0x72, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x2f, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x57, 0x68, 0x65, 0x6e, 0x53,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x48, 0x61, 0x76, 0x69, 0x6e, 0x67, 0x45, 0x72, 0x72, 0x52,
	0x65, 0x73, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x67, 0x6c, 0x69, 0x64, 0x65, 0x31, 0x30, 0x30, 0x2f, 0x64, 0x61, 0x6b, 0x2d, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_manager_scraper_proto_rawDescOnce sync.Once
	file_pb_svc_manager_scraper_proto_rawDescData = file_pb_svc_manager_scraper_proto_rawDesc
)

func file_pb_svc_manager_scraper_proto_rawDescGZIP() []byte {
	file_pb_svc_manager_scraper_proto_rawDescOnce.Do(func() {
		file_pb_svc_manager_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_manager_scraper_proto_rawDescData)
	})
	return file_pb_svc_manager_scraper_proto_rawDescData
}

var file_pb_svc_manager_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_svc_manager_scraper_proto_goTypes = []interface{}{
	(*WhenDoneScraperReq)(nil),      // 0: pb.svc.manager.scraper.WhenDoneScraperReq
	(*WhenDoneScraperRes)(nil),      // 1: pb.svc.manager.scraper.WhenDoneScraperRes
	(*WhenStartScraperReq)(nil),     // 2: pb.svc.manager.scraper.WhenStartScraperReq
	(*WhenStartScraperRes)(nil),     // 3: pb.svc.manager.scraper.WhenStartScraperRes
	(*WhenScraperHavingErrReq)(nil), // 4: pb.svc.manager.scraper.WhenScraperHavingErrReq
	(*WhenScraperHavingErrRes)(nil), // 5: pb.svc.manager.scraper.WhenScraperHavingErrRes
	(*WhenScraperHavingMsgReq)(nil), // 6: pb.svc.manager.scraper.WhenScraperHavingMsgReq
	(*WhenScraperHavingMsgRes)(nil), // 7: pb.svc.manager.scraper.WhenScraperHavingMsgRes
}
var file_pb_svc_manager_scraper_proto_depIdxs = []int32{
	2, // 0: pb.svc.manager.scraper.ScraperService.WhenStartScraper:input_type -> pb.svc.manager.scraper.WhenStartScraperReq
	0, // 1: pb.svc.manager.scraper.ScraperService.WhenDoneScraper:input_type -> pb.svc.manager.scraper.WhenDoneScraperReq
	6, // 2: pb.svc.manager.scraper.ScraperService.WhenScraperHavingMsg:input_type -> pb.svc.manager.scraper.WhenScraperHavingMsgReq
	4, // 3: pb.svc.manager.scraper.ScraperService.WhenScraperHavingErr:input_type -> pb.svc.manager.scraper.WhenScraperHavingErrReq
	3, // 4: pb.svc.manager.scraper.ScraperService.WhenStartScraper:output_type -> pb.svc.manager.scraper.WhenStartScraperRes
	1, // 5: pb.svc.manager.scraper.ScraperService.WhenDoneScraper:output_type -> pb.svc.manager.scraper.WhenDoneScraperRes
	7, // 6: pb.svc.manager.scraper.ScraperService.WhenScraperHavingMsg:output_type -> pb.svc.manager.scraper.WhenScraperHavingMsgRes
	5, // 7: pb.svc.manager.scraper.ScraperService.WhenScraperHavingErr:output_type -> pb.svc.manager.scraper.WhenScraperHavingErrRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_svc_manager_scraper_proto_init() }
func file_pb_svc_manager_scraper_proto_init() {
	if File_pb_svc_manager_scraper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_manager_scraper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhenDoneScraperReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_manager_scraper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhenDoneScraperRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_manager_scraper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhenStartScraperReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_manager_scraper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhenStartScraperRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_manager_scraper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhenScraperHavingErrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_manager_scraper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhenScraperHavingErrRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_manager_scraper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhenScraperHavingMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_manager_scraper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhenScraperHavingMsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_manager_scraper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_manager_scraper_proto_goTypes,
		DependencyIndexes: file_pb_svc_manager_scraper_proto_depIdxs,
		MessageInfos:      file_pb_svc_manager_scraper_proto_msgTypes,
	}.Build()
	File_pb_svc_manager_scraper_proto = out.File
	file_pb_svc_manager_scraper_proto_rawDesc = nil
	file_pb_svc_manager_scraper_proto_goTypes = nil
	file_pb_svc_manager_scraper_proto_depIdxs = nil
}
