// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/svc/analyzer.proto

package svc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartAnalyzerReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartAnalyzerReq) Reset()         { *m = StartAnalyzerReq{} }
func (m *StartAnalyzerReq) String() string { return proto.CompactTextString(m) }
func (*StartAnalyzerReq) ProtoMessage()    {}
func (*StartAnalyzerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e3e4d56ab82ba2f, []int{0}
}

func (m *StartAnalyzerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartAnalyzerReq.Unmarshal(m, b)
}
func (m *StartAnalyzerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartAnalyzerReq.Marshal(b, m, deterministic)
}
func (m *StartAnalyzerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartAnalyzerReq.Merge(m, src)
}
func (m *StartAnalyzerReq) XXX_Size() int {
	return xxx_messageInfo_StartAnalyzerReq.Size(m)
}
func (m *StartAnalyzerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartAnalyzerReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartAnalyzerReq proto.InternalMessageInfo

type StartAnalyzerRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartAnalyzerRes) Reset()         { *m = StartAnalyzerRes{} }
func (m *StartAnalyzerRes) String() string { return proto.CompactTextString(m) }
func (*StartAnalyzerRes) ProtoMessage()    {}
func (*StartAnalyzerRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e3e4d56ab82ba2f, []int{1}
}

func (m *StartAnalyzerRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartAnalyzerRes.Unmarshal(m, b)
}
func (m *StartAnalyzerRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartAnalyzerRes.Marshal(b, m, deterministic)
}
func (m *StartAnalyzerRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartAnalyzerRes.Merge(m, src)
}
func (m *StartAnalyzerRes) XXX_Size() int {
	return xxx_messageInfo_StartAnalyzerRes.Size(m)
}
func (m *StartAnalyzerRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StartAnalyzerRes.DiscardUnknown(m)
}

var xxx_messageInfo_StartAnalyzerRes proto.InternalMessageInfo

type GetStatusReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusReq) Reset()         { *m = GetStatusReq{} }
func (m *GetStatusReq) String() string { return proto.CompactTextString(m) }
func (*GetStatusReq) ProtoMessage()    {}
func (*GetStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e3e4d56ab82ba2f, []int{2}
}

func (m *GetStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusReq.Unmarshal(m, b)
}
func (m *GetStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusReq.Marshal(b, m, deterministic)
}
func (m *GetStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusReq.Merge(m, src)
}
func (m *GetStatusReq) XXX_Size() int {
	return xxx_messageInfo_GetStatusReq.Size(m)
}
func (m *GetStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusReq proto.InternalMessageInfo

type GetStatusRes struct {
	Current              int32    `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRes) Reset()         { *m = GetStatusRes{} }
func (m *GetStatusRes) String() string { return proto.CompactTextString(m) }
func (*GetStatusRes) ProtoMessage()    {}
func (*GetStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e3e4d56ab82ba2f, []int{3}
}

func (m *GetStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRes.Unmarshal(m, b)
}
func (m *GetStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRes.Marshal(b, m, deterministic)
}
func (m *GetStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRes.Merge(m, src)
}
func (m *GetStatusRes) XXX_Size() int {
	return xxx_messageInfo_GetStatusRes.Size(m)
}
func (m *GetStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRes proto.InternalMessageInfo

func (m *GetStatusRes) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *GetStatusRes) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*StartAnalyzerReq)(nil), "pb.svc.StartAnalyzerReq")
	proto.RegisterType((*StartAnalyzerRes)(nil), "pb.svc.StartAnalyzerRes")
	proto.RegisterType((*GetStatusReq)(nil), "pb.svc.GetStatusReq")
	proto.RegisterType((*GetStatusRes)(nil), "pb.svc.GetStatusRes")
}

func init() { proto.RegisterFile("pb/svc/analyzer.proto", fileDescriptor_9e3e4d56ab82ba2f) }

var fileDescriptor_9e3e4d56ab82ba2f = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x48, 0xd2, 0x2f,
	0x2e, 0x4b, 0xd6, 0x4f, 0xcc, 0x4b, 0xcc, 0xa9, 0xac, 0x4a, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x2b, 0x48, 0xd2, 0x2b, 0x2e, 0x4b, 0x56, 0x12, 0xe2, 0x12, 0x08, 0x2e, 0x49,
	0x2c, 0x2a, 0x71, 0x84, 0x4a, 0x07, 0xa5, 0x16, 0x62, 0x11, 0x2b, 0x56, 0xe2, 0xe3, 0xe2, 0x71,
	0x4f, 0x2d, 0x09, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x06, 0xa9, 0xb1, 0x43, 0xe1, 0x17, 0x0b, 0x49,
	0x70, 0xb1, 0x27, 0x97, 0x16, 0x15, 0xa5, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06,
	0xc1, 0xb8, 0x42, 0x22, 0x5c, 0xac, 0x25, 0xf9, 0x25, 0x89, 0x39, 0x12, 0x4c, 0x60, 0x71, 0x08,
	0xc7, 0xa8, 0x87, 0x91, 0x8b, 0x03, 0x66, 0xbe, 0x90, 0x2b, 0x17, 0x2f, 0x8a, 0x85, 0x42, 0x12,
	0x7a, 0x10, 0xe7, 0xe9, 0xa1, 0xbb, 0x4d, 0x0a, 0x97, 0x4c, 0xb1, 0x12, 0x83, 0x90, 0x25, 0x17,
	0x27, 0xdc, 0x4d, 0x42, 0x22, 0x30, 0x85, 0xc8, 0xce, 0x96, 0xc2, 0x26, 0x5a, 0xac, 0xc4, 0xe0,
	0xa4, 0x19, 0xa5, 0x9e, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x98,
	0x9e, 0x93, 0x99, 0x92, 0x6a, 0x68, 0x60, 0xa0, 0x9f, 0x92, 0x98, 0xad, 0x9b, 0x9d, 0x5a, 0x59,
	0x9e, 0x5f, 0x94, 0xa2, 0x0f, 0x09, 0xc8, 0x24, 0x36, 0x70, 0x00, 0x1a, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x81, 0x7a, 0x0c, 0x70, 0x59, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnalyzerClient is the client API for Analyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalyzerClient interface {
	StartAnalyzer(ctx context.Context, in *StartAnalyzerReq, opts ...grpc.CallOption) (*StartAnalyzerRes, error)
	GetStatus(ctx context.Context, in *GetStatusReq, opts ...grpc.CallOption) (*GetStatusRes, error)
}

type analyzerClient struct {
	cc *grpc.ClientConn
}

func NewAnalyzerClient(cc *grpc.ClientConn) AnalyzerClient {
	return &analyzerClient{cc}
}

func (c *analyzerClient) StartAnalyzer(ctx context.Context, in *StartAnalyzerReq, opts ...grpc.CallOption) (*StartAnalyzerRes, error) {
	out := new(StartAnalyzerRes)
	err := c.cc.Invoke(ctx, "/pb.svc.Analyzer/StartAnalyzer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerClient) GetStatus(ctx context.Context, in *GetStatusReq, opts ...grpc.CallOption) (*GetStatusRes, error) {
	out := new(GetStatusRes)
	err := c.cc.Invoke(ctx, "/pb.svc.Analyzer/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyzerServer is the server API for Analyzer service.
type AnalyzerServer interface {
	StartAnalyzer(context.Context, *StartAnalyzerReq) (*StartAnalyzerRes, error)
	GetStatus(context.Context, *GetStatusReq) (*GetStatusRes, error)
}

// UnimplementedAnalyzerServer can be embedded to have forward compatible implementations.
type UnimplementedAnalyzerServer struct {
}

func (*UnimplementedAnalyzerServer) StartAnalyzer(ctx context.Context, req *StartAnalyzerReq) (*StartAnalyzerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAnalyzer not implemented")
}
func (*UnimplementedAnalyzerServer) GetStatus(ctx context.Context, req *GetStatusReq) (*GetStatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}

func RegisterAnalyzerServer(s *grpc.Server, srv AnalyzerServer) {
	s.RegisterService(&_Analyzer_serviceDesc, srv)
}

func _Analyzer_StartAnalyzer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAnalyzerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).StartAnalyzer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.Analyzer/StartAnalyzer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).StartAnalyzer(ctx, req.(*StartAnalyzerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analyzer_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.Analyzer/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).GetStatus(ctx, req.(*GetStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Analyzer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.svc.Analyzer",
	HandlerType: (*AnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartAnalyzer",
			Handler:    _Analyzer_StartAnalyzer_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Analyzer_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/svc/analyzer.proto",
}
