// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/svc/provision.proto

package svc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateScraperReq struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateScraperReq) Reset()         { *m = CreateScraperReq{} }
func (m *CreateScraperReq) String() string { return proto.CompactTextString(m) }
func (*CreateScraperReq) ProtoMessage()    {}
func (*CreateScraperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fb79dcd2f7447a4, []int{0}
}

func (m *CreateScraperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateScraperReq.Unmarshal(m, b)
}
func (m *CreateScraperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateScraperReq.Marshal(b, m, deterministic)
}
func (m *CreateScraperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScraperReq.Merge(m, src)
}
func (m *CreateScraperReq) XXX_Size() int {
	return xxx_messageInfo_CreateScraperReq.Size(m)
}
func (m *CreateScraperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScraperReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScraperReq proto.InternalMessageInfo

func (m *CreateScraperReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *CreateScraperReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type CreateScraperRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateScraperRes) Reset()         { *m = CreateScraperRes{} }
func (m *CreateScraperRes) String() string { return proto.CompactTextString(m) }
func (*CreateScraperRes) ProtoMessage()    {}
func (*CreateScraperRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fb79dcd2f7447a4, []int{1}
}

func (m *CreateScraperRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateScraperRes.Unmarshal(m, b)
}
func (m *CreateScraperRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateScraperRes.Marshal(b, m, deterministic)
}
func (m *CreateScraperRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScraperRes.Merge(m, src)
}
func (m *CreateScraperRes) XXX_Size() int {
	return xxx_messageInfo_CreateScraperRes.Size(m)
}
func (m *CreateScraperRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScraperRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScraperRes proto.InternalMessageInfo

type CreateAnalyzerReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnalyzerReq) Reset()         { *m = CreateAnalyzerReq{} }
func (m *CreateAnalyzerReq) String() string { return proto.CompactTextString(m) }
func (*CreateAnalyzerReq) ProtoMessage()    {}
func (*CreateAnalyzerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fb79dcd2f7447a4, []int{2}
}

func (m *CreateAnalyzerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnalyzerReq.Unmarshal(m, b)
}
func (m *CreateAnalyzerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnalyzerReq.Marshal(b, m, deterministic)
}
func (m *CreateAnalyzerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnalyzerReq.Merge(m, src)
}
func (m *CreateAnalyzerReq) XXX_Size() int {
	return xxx_messageInfo_CreateAnalyzerReq.Size(m)
}
func (m *CreateAnalyzerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnalyzerReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnalyzerReq proto.InternalMessageInfo

func (m *CreateAnalyzerReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateAnalyzerRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnalyzerRes) Reset()         { *m = CreateAnalyzerRes{} }
func (m *CreateAnalyzerRes) String() string { return proto.CompactTextString(m) }
func (*CreateAnalyzerRes) ProtoMessage()    {}
func (*CreateAnalyzerRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fb79dcd2f7447a4, []int{3}
}

func (m *CreateAnalyzerRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnalyzerRes.Unmarshal(m, b)
}
func (m *CreateAnalyzerRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnalyzerRes.Marshal(b, m, deterministic)
}
func (m *CreateAnalyzerRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnalyzerRes.Merge(m, src)
}
func (m *CreateAnalyzerRes) XXX_Size() int {
	return xxx_messageInfo_CreateAnalyzerRes.Size(m)
}
func (m *CreateAnalyzerRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnalyzerRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnalyzerRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateScraperReq)(nil), "pb.svc.CreateScraperReq")
	proto.RegisterType((*CreateScraperRes)(nil), "pb.svc.CreateScraperRes")
	proto.RegisterType((*CreateAnalyzerReq)(nil), "pb.svc.CreateAnalyzerReq")
	proto.RegisterType((*CreateAnalyzerRes)(nil), "pb.svc.CreateAnalyzerRes")
}

func init() { proto.RegisterFile("pb/svc/provision.proto", fileDescriptor_8fb79dcd2f7447a4) }

var fileDescriptor_8fb79dcd2f7447a4 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x48, 0xd2, 0x2f,
	0x2e, 0x4b, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xcb, 0x2c, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x48, 0xd2, 0x2b, 0x2e, 0x4b, 0x56, 0x72, 0xe2, 0x12, 0x70, 0x2e,
	0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x4e, 0x2e, 0x4a, 0x2c, 0x48, 0x2d, 0x0a, 0x4a, 0x2d, 0x14, 0x92,
	0xe0, 0x62, 0xcf, 0x4e, 0xad, 0x2c, 0xcf, 0x2f, 0x4a, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0x71, 0x85, 0x44, 0xb8, 0x58, 0xf3, 0xcb, 0xf3, 0x52, 0x8b, 0x24, 0x98, 0xc0, 0xe2, 0x10,
	0x8e, 0x92, 0x10, 0x86, 0x19, 0xc5, 0x4a, 0xca, 0x5c, 0x82, 0x10, 0x31, 0xc7, 0xbc, 0xc4, 0x9c,
	0xca, 0x2a, 0x88, 0xc1, 0x7c, 0x5c, 0x4c, 0x99, 0x30, 0x33, 0x99, 0x32, 0x53, 0x94, 0x84, 0x31,
	0x15, 0x15, 0x1b, 0xcd, 0x61, 0xe4, 0xe2, 0x0c, 0x80, 0xb9, 0x56, 0xc8, 0x95, 0x8b, 0x17, 0xc5,
	0x6c, 0x21, 0x09, 0x3d, 0x88, 0xcb, 0xf5, 0xd0, 0x9d, 0x2d, 0x85, 0x4b, 0xa6, 0x58, 0x89, 0x41,
	0xc8, 0x83, 0x8b, 0x0f, 0xd5, 0x26, 0x21, 0x49, 0x54, 0xd5, 0x48, 0xce, 0x94, 0xc2, 0x29, 0x55,
	0xac, 0xc4, 0xe0, 0xa4, 0x19, 0xa5, 0x9e, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f,
	0xab, 0x9f, 0x98, 0x9e, 0x93, 0x99, 0x92, 0x6a, 0x68, 0x60, 0xa0, 0x9f, 0x92, 0x98, 0xad, 0x0b,
	0x0d, 0x26, 0x7d, 0x48, 0x98, 0x27, 0xb1, 0x81, 0x83, 0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x70, 0x38, 0xc2, 0x7d, 0x84, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProvisionClient is the client API for Provision service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProvisionClient interface {
	CreateScraper(ctx context.Context, in *CreateScraperReq, opts ...grpc.CallOption) (*CreateScraperRes, error)
	CreateAnalyzer(ctx context.Context, in *CreateAnalyzerReq, opts ...grpc.CallOption) (*CreateAnalyzerRes, error)
}

type provisionClient struct {
	cc *grpc.ClientConn
}

func NewProvisionClient(cc *grpc.ClientConn) ProvisionClient {
	return &provisionClient{cc}
}

func (c *provisionClient) CreateScraper(ctx context.Context, in *CreateScraperReq, opts ...grpc.CallOption) (*CreateScraperRes, error) {
	out := new(CreateScraperRes)
	err := c.cc.Invoke(ctx, "/pb.svc.Provision/CreateScraper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionClient) CreateAnalyzer(ctx context.Context, in *CreateAnalyzerReq, opts ...grpc.CallOption) (*CreateAnalyzerRes, error) {
	out := new(CreateAnalyzerRes)
	err := c.cc.Invoke(ctx, "/pb.svc.Provision/CreateAnalyzer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionServer is the server API for Provision service.
type ProvisionServer interface {
	CreateScraper(context.Context, *CreateScraperReq) (*CreateScraperRes, error)
	CreateAnalyzer(context.Context, *CreateAnalyzerReq) (*CreateAnalyzerRes, error)
}

// UnimplementedProvisionServer can be embedded to have forward compatible implementations.
type UnimplementedProvisionServer struct {
}

func (*UnimplementedProvisionServer) CreateScraper(ctx context.Context, req *CreateScraperReq) (*CreateScraperRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScraper not implemented")
}
func (*UnimplementedProvisionServer) CreateAnalyzer(ctx context.Context, req *CreateAnalyzerReq) (*CreateAnalyzerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAnalyzer not implemented")
}

func RegisterProvisionServer(s *grpc.Server, srv ProvisionServer) {
	s.RegisterService(&_Provision_serviceDesc, srv)
}

func _Provision_CreateScraper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScraperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).CreateScraper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.Provision/CreateScraper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).CreateScraper(ctx, req.(*CreateScraperReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provision_CreateAnalyzer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnalyzerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).CreateAnalyzer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.Provision/CreateAnalyzer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).CreateAnalyzer(ctx, req.(*CreateAnalyzerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provision_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.svc.Provision",
	HandlerType: (*ProvisionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateScraper",
			Handler:    _Provision_CreateScraper_Handler,
		},
		{
			MethodName: "CreateAnalyzer",
			Handler:    _Provision_CreateAnalyzer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/svc/provision.proto",
}
