// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: pb/svc/runner.proto

package svc

import (
	runner "github.com/aglide100/dak-keyword/pb/runner"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRunnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Runner *runner.Runner `protobuf:"bytes,1,opt,name=Runner,proto3" json:"Runner,omitempty"`
}

func (x *CreateRunnerReq) Reset() {
	*x = CreateRunnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_runner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRunnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunnerReq) ProtoMessage() {}

func (x *CreateRunnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_runner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunnerReq.ProtoReflect.Descriptor instead.
func (*CreateRunnerReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_runner_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRunnerReq) GetRunner() *runner.Runner {
	if x != nil {
		return x.Runner
	}
	return nil
}

type CreateRunnerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRunnerRes) Reset() {
	*x = CreateRunnerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_runner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRunnerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunnerRes) ProtoMessage() {}

func (x *CreateRunnerRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_runner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunnerRes.ProtoReflect.Descriptor instead.
func (*CreateRunnerRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_runner_proto_rawDescGZIP(), []int{1}
}

type GetRunnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRunnerReq) Reset() {
	*x = GetRunnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_runner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRunnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnerReq) ProtoMessage() {}

func (x *GetRunnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_runner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnerReq.ProtoReflect.Descriptor instead.
func (*GetRunnerReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_runner_proto_rawDescGZIP(), []int{2}
}

type GetRunnerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRunnerRes) Reset() {
	*x = GetRunnerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_runner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRunnerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnerRes) ProtoMessage() {}

func (x *GetRunnerRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_runner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnerRes.ProtoReflect.Descriptor instead.
func (*GetRunnerRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_runner_proto_rawDescGZIP(), []int{3}
}

type DeleteRunnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRunnerReq) Reset() {
	*x = DeleteRunnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_runner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRunnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunnerReq) ProtoMessage() {}

func (x *DeleteRunnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_runner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunnerReq.ProtoReflect.Descriptor instead.
func (*DeleteRunnerReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_runner_proto_rawDescGZIP(), []int{4}
}

type DeleteRunnerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRunnerRes) Reset() {
	*x = DeleteRunnerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_runner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRunnerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunnerRes) ProtoMessage() {}

func (x *DeleteRunnerRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_runner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunnerRes.ProtoReflect.Descriptor instead.
func (*DeleteRunnerRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_runner_proto_rawDescGZIP(), []int{5}
}

var File_pb_svc_runner_proto protoreflect.FileDescriptor

var file_pb_svc_runner_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x76, 0x2e, 0x73, 0x76, 0x63, 0x1a, 0x16, 0x70,
	0x62, 0x2f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x61, 0x6b, 0x5f, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x11, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22,
	0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22,
	0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22,
	0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x32, 0xc5, 0x01, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x40, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0x12, 0x17, 0x2e, 0x70, 0x76, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x76, 0x2e, 0x73,
	0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x12, 0x37, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x14, 0x2e, 0x70, 0x76, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x76, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x76,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x76, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x42, 0x08, 0x5a,
	0x06, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_runner_proto_rawDescOnce sync.Once
	file_pb_svc_runner_proto_rawDescData = file_pb_svc_runner_proto_rawDesc
)

func file_pb_svc_runner_proto_rawDescGZIP() []byte {
	file_pb_svc_runner_proto_rawDescOnce.Do(func() {
		file_pb_svc_runner_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_runner_proto_rawDescData)
	})
	return file_pb_svc_runner_proto_rawDescData
}

var file_pb_svc_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_svc_runner_proto_goTypes = []interface{}{
	(*CreateRunnerReq)(nil), // 0: pv.svc.CreateRunnerReq
	(*CreateRunnerRes)(nil), // 1: pv.svc.CreateRunnerRes
	(*GetRunnerReq)(nil),    // 2: pv.svc.GetRunnerReq
	(*GetRunnerRes)(nil),    // 3: pv.svc.GetRunnerRes
	(*DeleteRunnerReq)(nil), // 4: pv.svc.DeleteRunnerReq
	(*DeleteRunnerRes)(nil), // 5: pv.svc.DeleteRunnerRes
	(*runner.Runner)(nil),   // 6: dak_keyword.runner.Runner
}
var file_pb_svc_runner_proto_depIdxs = []int32{
	6, // 0: pv.svc.CreateRunnerReq.Runner:type_name -> dak_keyword.runner.Runner
	0, // 1: pv.svc.Runner.CreateRunner:input_type -> pv.svc.CreateRunnerReq
	2, // 2: pv.svc.Runner.GetRunner:input_type -> pv.svc.GetRunnerReq
	4, // 3: pv.svc.Runner.DeleteRunner:input_type -> pv.svc.DeleteRunnerReq
	1, // 4: pv.svc.Runner.CreateRunner:output_type -> pv.svc.CreateRunnerRes
	3, // 5: pv.svc.Runner.GetRunner:output_type -> pv.svc.GetRunnerRes
	5, // 6: pv.svc.Runner.DeleteRunner:output_type -> pv.svc.DeleteRunnerRes
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_svc_runner_proto_init() }
func file_pb_svc_runner_proto_init() {
	if File_pb_svc_runner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_runner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRunnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_runner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRunnerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_runner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRunnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_runner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRunnerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_runner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRunnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_runner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRunnerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_runner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_runner_proto_goTypes,
		DependencyIndexes: file_pb_svc_runner_proto_depIdxs,
		MessageInfos:      file_pb_svc_runner_proto_msgTypes,
	}.Build()
	File_pb_svc_runner_proto = out.File
	file_pb_svc_runner_proto_rawDesc = nil
	file_pb_svc_runner_proto_goTypes = nil
	file_pb_svc_runner_proto_depIdxs = nil
}
