// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: pb/svc/runner.proto

package svc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RunnerClient is the client API for Runner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerClient interface {
	CreateRunner(ctx context.Context, in *CreateRunnerReq, opts ...grpc.CallOption) (*CreateRunnerRes, error)
	GetRunner(ctx context.Context, in *GetRunnerReq, opts ...grpc.CallOption) (*GetRunnerRes, error)
	DeleteRunner(ctx context.Context, in *DeleteRunnerReq, opts ...grpc.CallOption) (*DeleteRunnerRes, error)
}

type runnerClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerClient(cc grpc.ClientConnInterface) RunnerClient {
	return &runnerClient{cc}
}

func (c *runnerClient) CreateRunner(ctx context.Context, in *CreateRunnerReq, opts ...grpc.CallOption) (*CreateRunnerRes, error) {
	out := new(CreateRunnerRes)
	err := c.cc.Invoke(ctx, "/pv.svc.Runner/CreateRunner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) GetRunner(ctx context.Context, in *GetRunnerReq, opts ...grpc.CallOption) (*GetRunnerRes, error) {
	out := new(GetRunnerRes)
	err := c.cc.Invoke(ctx, "/pv.svc.Runner/GetRunner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) DeleteRunner(ctx context.Context, in *DeleteRunnerReq, opts ...grpc.CallOption) (*DeleteRunnerRes, error) {
	out := new(DeleteRunnerRes)
	err := c.cc.Invoke(ctx, "/pv.svc.Runner/DeleteRunner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerServer is the server API for Runner service.
// All implementations must embed UnimplementedRunnerServer
// for forward compatibility
type RunnerServer interface {
	CreateRunner(context.Context, *CreateRunnerReq) (*CreateRunnerRes, error)
	GetRunner(context.Context, *GetRunnerReq) (*GetRunnerRes, error)
	DeleteRunner(context.Context, *DeleteRunnerReq) (*DeleteRunnerRes, error)
	mustEmbedUnimplementedRunnerServer()
}

// UnimplementedRunnerServer must be embedded to have forward compatible implementations.
type UnimplementedRunnerServer struct {
}

func (UnimplementedRunnerServer) CreateRunner(context.Context, *CreateRunnerReq) (*CreateRunnerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRunner not implemented")
}
func (UnimplementedRunnerServer) GetRunner(context.Context, *GetRunnerReq) (*GetRunnerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunner not implemented")
}
func (UnimplementedRunnerServer) DeleteRunner(context.Context, *DeleteRunnerReq) (*DeleteRunnerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRunner not implemented")
}
func (UnimplementedRunnerServer) mustEmbedUnimplementedRunnerServer() {}

// UnsafeRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServer will
// result in compilation errors.
type UnsafeRunnerServer interface {
	mustEmbedUnimplementedRunnerServer()
}

func RegisterRunnerServer(s grpc.ServiceRegistrar, srv RunnerServer) {
	s.RegisterService(&Runner_ServiceDesc, srv)
}

func _Runner_CreateRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRunnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).CreateRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pv.svc.Runner/CreateRunner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).CreateRunner(ctx, req.(*CreateRunnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_GetRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).GetRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pv.svc.Runner/GetRunner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).GetRunner(ctx, req.(*GetRunnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_DeleteRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRunnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).DeleteRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pv.svc.Runner/DeleteRunner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).DeleteRunner(ctx, req.(*DeleteRunnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Runner_ServiceDesc is the grpc.ServiceDesc for Runner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pv.svc.Runner",
	HandlerType: (*RunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRunner",
			Handler:    _Runner_CreateRunner_Handler,
		},
		{
			MethodName: "GetRunner",
			Handler:    _Runner_GetRunner_Handler,
		},
		{
			MethodName: "DeleteRunner",
			Handler:    _Runner_DeleteRunner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/svc/runner.proto",
}
