// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: pb/svc/manager/analyzer.proto

package analyzer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnalyzerServiceClient is the client API for AnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyzerServiceClient interface {
	WhenStartAnalyzer(ctx context.Context, in *WhenStartAnalyzerReq, opts ...grpc.CallOption) (*WhenStartAnalyzerRes, error)
	WhenDoneAnalyzer(ctx context.Context, in *WhenDoneAnalyzerReq, opts ...grpc.CallOption) (*WhenDoneAnalyzerRes, error)
	WhenAnalyzerHavingErr(ctx context.Context, in *WhenAnalyzerHavingErrReq, opts ...grpc.CallOption) (*WhenAnalyzerHavingErrRes, error)
	WhenAnalyzerHavingMsg(ctx context.Context, in *WhenAnalyzerHavingMsgReq, opts ...grpc.CallOption) (*WhenAnalyzerHavingMsgRes, error)
}

type analyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyzerServiceClient(cc grpc.ClientConnInterface) AnalyzerServiceClient {
	return &analyzerServiceClient{cc}
}

func (c *analyzerServiceClient) WhenStartAnalyzer(ctx context.Context, in *WhenStartAnalyzerReq, opts ...grpc.CallOption) (*WhenStartAnalyzerRes, error) {
	out := new(WhenStartAnalyzerRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.analyzer.AnalyzerService/WhenStartAnalyzer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) WhenDoneAnalyzer(ctx context.Context, in *WhenDoneAnalyzerReq, opts ...grpc.CallOption) (*WhenDoneAnalyzerRes, error) {
	out := new(WhenDoneAnalyzerRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.analyzer.AnalyzerService/WhenDoneAnalyzer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) WhenAnalyzerHavingErr(ctx context.Context, in *WhenAnalyzerHavingErrReq, opts ...grpc.CallOption) (*WhenAnalyzerHavingErrRes, error) {
	out := new(WhenAnalyzerHavingErrRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.analyzer.AnalyzerService/WhenAnalyzerHavingErr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) WhenAnalyzerHavingMsg(ctx context.Context, in *WhenAnalyzerHavingMsgReq, opts ...grpc.CallOption) (*WhenAnalyzerHavingMsgRes, error) {
	out := new(WhenAnalyzerHavingMsgRes)
	err := c.cc.Invoke(ctx, "/pb.svc.manager.analyzer.AnalyzerService/WhenAnalyzerHavingMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyzerServiceServer is the server API for AnalyzerService service.
// All implementations must embed UnimplementedAnalyzerServiceServer
// for forward compatibility
type AnalyzerServiceServer interface {
	WhenStartAnalyzer(context.Context, *WhenStartAnalyzerReq) (*WhenStartAnalyzerRes, error)
	WhenDoneAnalyzer(context.Context, *WhenDoneAnalyzerReq) (*WhenDoneAnalyzerRes, error)
	WhenAnalyzerHavingErr(context.Context, *WhenAnalyzerHavingErrReq) (*WhenAnalyzerHavingErrRes, error)
	WhenAnalyzerHavingMsg(context.Context, *WhenAnalyzerHavingMsgReq) (*WhenAnalyzerHavingMsgRes, error)
	mustEmbedUnimplementedAnalyzerServiceServer()
}

// UnimplementedAnalyzerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyzerServiceServer struct {
}

func (UnimplementedAnalyzerServiceServer) WhenStartAnalyzer(context.Context, *WhenStartAnalyzerReq) (*WhenStartAnalyzerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhenStartAnalyzer not implemented")
}
func (UnimplementedAnalyzerServiceServer) WhenDoneAnalyzer(context.Context, *WhenDoneAnalyzerReq) (*WhenDoneAnalyzerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhenDoneAnalyzer not implemented")
}
func (UnimplementedAnalyzerServiceServer) WhenAnalyzerHavingErr(context.Context, *WhenAnalyzerHavingErrReq) (*WhenAnalyzerHavingErrRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhenAnalyzerHavingErr not implemented")
}
func (UnimplementedAnalyzerServiceServer) WhenAnalyzerHavingMsg(context.Context, *WhenAnalyzerHavingMsgReq) (*WhenAnalyzerHavingMsgRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhenAnalyzerHavingMsg not implemented")
}
func (UnimplementedAnalyzerServiceServer) mustEmbedUnimplementedAnalyzerServiceServer() {}

// UnsafeAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyzerServiceServer will
// result in compilation errors.
type UnsafeAnalyzerServiceServer interface {
	mustEmbedUnimplementedAnalyzerServiceServer()
}

func RegisterAnalyzerServiceServer(s grpc.ServiceRegistrar, srv AnalyzerServiceServer) {
	s.RegisterService(&AnalyzerService_ServiceDesc, srv)
}

func _AnalyzerService_WhenStartAnalyzer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhenStartAnalyzerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).WhenStartAnalyzer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.analyzer.AnalyzerService/WhenStartAnalyzer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).WhenStartAnalyzer(ctx, req.(*WhenStartAnalyzerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_WhenDoneAnalyzer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhenDoneAnalyzerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).WhenDoneAnalyzer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.analyzer.AnalyzerService/WhenDoneAnalyzer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).WhenDoneAnalyzer(ctx, req.(*WhenDoneAnalyzerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_WhenAnalyzerHavingErr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhenAnalyzerHavingErrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).WhenAnalyzerHavingErr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.analyzer.AnalyzerService/WhenAnalyzerHavingErr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).WhenAnalyzerHavingErr(ctx, req.(*WhenAnalyzerHavingErrReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_WhenAnalyzerHavingMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhenAnalyzerHavingMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).WhenAnalyzerHavingMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.manager.analyzer.AnalyzerService/WhenAnalyzerHavingMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).WhenAnalyzerHavingMsg(ctx, req.(*WhenAnalyzerHavingMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyzerService_ServiceDesc is the grpc.ServiceDesc for AnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.svc.manager.analyzer.AnalyzerService",
	HandlerType: (*AnalyzerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhenStartAnalyzer",
			Handler:    _AnalyzerService_WhenStartAnalyzer_Handler,
		},
		{
			MethodName: "WhenDoneAnalyzer",
			Handler:    _AnalyzerService_WhenDoneAnalyzer_Handler,
		},
		{
			MethodName: "WhenAnalyzerHavingErr",
			Handler:    _AnalyzerService_WhenAnalyzerHavingErr_Handler,
		},
		{
			MethodName: "WhenAnalyzerHavingMsg",
			Handler:    _AnalyzerService_WhenAnalyzerHavingMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/svc/manager/analyzer.proto",
}
