// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/svc/provision/provision.proto

package provision

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateScraperReq struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	WorkerId             string   `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId                string   `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateScraperReq) Reset()         { *m = CreateScraperReq{} }
func (m *CreateScraperReq) String() string { return proto.CompactTextString(m) }
func (*CreateScraperReq) ProtoMessage()    {}
func (*CreateScraperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{0}
}

func (m *CreateScraperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateScraperReq.Unmarshal(m, b)
}
func (m *CreateScraperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateScraperReq.Marshal(b, m, deterministic)
}
func (m *CreateScraperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScraperReq.Merge(m, src)
}
func (m *CreateScraperReq) XXX_Size() int {
	return xxx_messageInfo_CreateScraperReq.Size(m)
}
func (m *CreateScraperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScraperReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScraperReq proto.InternalMessageInfo

func (m *CreateScraperReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *CreateScraperReq) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

func (m *CreateScraperReq) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type CreateScraperRes struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateScraperRes) Reset()         { *m = CreateScraperRes{} }
func (m *CreateScraperRes) String() string { return proto.CompactTextString(m) }
func (*CreateScraperRes) ProtoMessage()    {}
func (*CreateScraperRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{1}
}

func (m *CreateScraperRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateScraperRes.Unmarshal(m, b)
}
func (m *CreateScraperRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateScraperRes.Marshal(b, m, deterministic)
}
func (m *CreateScraperRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScraperRes.Merge(m, src)
}
func (m *CreateScraperRes) XXX_Size() int {
	return xxx_messageInfo_CreateScraperRes.Size(m)
}
func (m *CreateScraperRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScraperRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScraperRes proto.InternalMessageInfo

func (m *CreateScraperRes) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CreateAnalyzerReq struct {
	ScraperId            string   `protobuf:"bytes,1,opt,name=scraperId,proto3" json:"scraperId,omitempty"`
	Keyword              string   `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnalyzerReq) Reset()         { *m = CreateAnalyzerReq{} }
func (m *CreateAnalyzerReq) String() string { return proto.CompactTextString(m) }
func (*CreateAnalyzerReq) ProtoMessage()    {}
func (*CreateAnalyzerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{2}
}

func (m *CreateAnalyzerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnalyzerReq.Unmarshal(m, b)
}
func (m *CreateAnalyzerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnalyzerReq.Marshal(b, m, deterministic)
}
func (m *CreateAnalyzerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnalyzerReq.Merge(m, src)
}
func (m *CreateAnalyzerReq) XXX_Size() int {
	return xxx_messageInfo_CreateAnalyzerReq.Size(m)
}
func (m *CreateAnalyzerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnalyzerReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnalyzerReq proto.InternalMessageInfo

func (m *CreateAnalyzerReq) GetScraperId() string {
	if m != nil {
		return m.ScraperId
	}
	return ""
}

func (m *CreateAnalyzerReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type CreateAnalyzerRes struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnalyzerRes) Reset()         { *m = CreateAnalyzerRes{} }
func (m *CreateAnalyzerRes) String() string { return proto.CompactTextString(m) }
func (*CreateAnalyzerRes) ProtoMessage()    {}
func (*CreateAnalyzerRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{3}
}

func (m *CreateAnalyzerRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnalyzerRes.Unmarshal(m, b)
}
func (m *CreateAnalyzerRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnalyzerRes.Marshal(b, m, deterministic)
}
func (m *CreateAnalyzerRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnalyzerRes.Merge(m, src)
}
func (m *CreateAnalyzerRes) XXX_Size() int {
	return xxx_messageInfo_CreateAnalyzerRes.Size(m)
}
func (m *CreateAnalyzerRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnalyzerRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnalyzerRes proto.InternalMessageInfo

func (m *CreateAnalyzerRes) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetScraperStatusReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetScraperStatusReq) Reset()         { *m = GetScraperStatusReq{} }
func (m *GetScraperStatusReq) String() string { return proto.CompactTextString(m) }
func (*GetScraperStatusReq) ProtoMessage()    {}
func (*GetScraperStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{4}
}

func (m *GetScraperStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScraperStatusReq.Unmarshal(m, b)
}
func (m *GetScraperStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScraperStatusReq.Marshal(b, m, deterministic)
}
func (m *GetScraperStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScraperStatusReq.Merge(m, src)
}
func (m *GetScraperStatusReq) XXX_Size() int {
	return xxx_messageInfo_GetScraperStatusReq.Size(m)
}
func (m *GetScraperStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScraperStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetScraperStatusReq proto.InternalMessageInfo

func (m *GetScraperStatusReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetScraperStatusRes struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetScraperStatusRes) Reset()         { *m = GetScraperStatusRes{} }
func (m *GetScraperStatusRes) String() string { return proto.CompactTextString(m) }
func (*GetScraperStatusRes) ProtoMessage()    {}
func (*GetScraperStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{5}
}

func (m *GetScraperStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScraperStatusRes.Unmarshal(m, b)
}
func (m *GetScraperStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScraperStatusRes.Marshal(b, m, deterministic)
}
func (m *GetScraperStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScraperStatusRes.Merge(m, src)
}
func (m *GetScraperStatusRes) XXX_Size() int {
	return xxx_messageInfo_GetScraperStatusRes.Size(m)
}
func (m *GetScraperStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScraperStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetScraperStatusRes proto.InternalMessageInfo

func (m *GetScraperStatusRes) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetAnalyzerStatusReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnalyzerStatusReq) Reset()         { *m = GetAnalyzerStatusReq{} }
func (m *GetAnalyzerStatusReq) String() string { return proto.CompactTextString(m) }
func (*GetAnalyzerStatusReq) ProtoMessage()    {}
func (*GetAnalyzerStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{6}
}

func (m *GetAnalyzerStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnalyzerStatusReq.Unmarshal(m, b)
}
func (m *GetAnalyzerStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnalyzerStatusReq.Marshal(b, m, deterministic)
}
func (m *GetAnalyzerStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnalyzerStatusReq.Merge(m, src)
}
func (m *GetAnalyzerStatusReq) XXX_Size() int {
	return xxx_messageInfo_GetAnalyzerStatusReq.Size(m)
}
func (m *GetAnalyzerStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnalyzerStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnalyzerStatusReq proto.InternalMessageInfo

func (m *GetAnalyzerStatusReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAnalyzerStatusRes struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnalyzerStatusRes) Reset()         { *m = GetAnalyzerStatusRes{} }
func (m *GetAnalyzerStatusRes) String() string { return proto.CompactTextString(m) }
func (*GetAnalyzerStatusRes) ProtoMessage()    {}
func (*GetAnalyzerStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{7}
}

func (m *GetAnalyzerStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnalyzerStatusRes.Unmarshal(m, b)
}
func (m *GetAnalyzerStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnalyzerStatusRes.Marshal(b, m, deterministic)
}
func (m *GetAnalyzerStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnalyzerStatusRes.Merge(m, src)
}
func (m *GetAnalyzerStatusRes) XXX_Size() int {
	return xxx_messageInfo_GetAnalyzerStatusRes.Size(m)
}
func (m *GetAnalyzerStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnalyzerStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnalyzerStatusRes proto.InternalMessageInfo

func (m *GetAnalyzerStatusRes) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RemoveScraperReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveScraperReq) Reset()         { *m = RemoveScraperReq{} }
func (m *RemoveScraperReq) String() string { return proto.CompactTextString(m) }
func (*RemoveScraperReq) ProtoMessage()    {}
func (*RemoveScraperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{8}
}

func (m *RemoveScraperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveScraperReq.Unmarshal(m, b)
}
func (m *RemoveScraperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveScraperReq.Marshal(b, m, deterministic)
}
func (m *RemoveScraperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveScraperReq.Merge(m, src)
}
func (m *RemoveScraperReq) XXX_Size() int {
	return xxx_messageInfo_RemoveScraperReq.Size(m)
}
func (m *RemoveScraperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveScraperReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveScraperReq proto.InternalMessageInfo

func (m *RemoveScraperReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveScraperRes struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveScraperRes) Reset()         { *m = RemoveScraperRes{} }
func (m *RemoveScraperRes) String() string { return proto.CompactTextString(m) }
func (*RemoveScraperRes) ProtoMessage()    {}
func (*RemoveScraperRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{9}
}

func (m *RemoveScraperRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveScraperRes.Unmarshal(m, b)
}
func (m *RemoveScraperRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveScraperRes.Marshal(b, m, deterministic)
}
func (m *RemoveScraperRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveScraperRes.Merge(m, src)
}
func (m *RemoveScraperRes) XXX_Size() int {
	return xxx_messageInfo_RemoveScraperRes.Size(m)
}
func (m *RemoveScraperRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveScraperRes.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveScraperRes proto.InternalMessageInfo

func (m *RemoveScraperRes) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RemoveAnalyzerReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAnalyzerReq) Reset()         { *m = RemoveAnalyzerReq{} }
func (m *RemoveAnalyzerReq) String() string { return proto.CompactTextString(m) }
func (*RemoveAnalyzerReq) ProtoMessage()    {}
func (*RemoveAnalyzerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{10}
}

func (m *RemoveAnalyzerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAnalyzerReq.Unmarshal(m, b)
}
func (m *RemoveAnalyzerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAnalyzerReq.Marshal(b, m, deterministic)
}
func (m *RemoveAnalyzerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAnalyzerReq.Merge(m, src)
}
func (m *RemoveAnalyzerReq) XXX_Size() int {
	return xxx_messageInfo_RemoveAnalyzerReq.Size(m)
}
func (m *RemoveAnalyzerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAnalyzerReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAnalyzerReq proto.InternalMessageInfo

func (m *RemoveAnalyzerReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveAnalyzerRes struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAnalyzerRes) Reset()         { *m = RemoveAnalyzerRes{} }
func (m *RemoveAnalyzerRes) String() string { return proto.CompactTextString(m) }
func (*RemoveAnalyzerRes) ProtoMessage()    {}
func (*RemoveAnalyzerRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a83c3d0d414ae9b, []int{11}
}

func (m *RemoveAnalyzerRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAnalyzerRes.Unmarshal(m, b)
}
func (m *RemoveAnalyzerRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAnalyzerRes.Marshal(b, m, deterministic)
}
func (m *RemoveAnalyzerRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAnalyzerRes.Merge(m, src)
}
func (m *RemoveAnalyzerRes) XXX_Size() int {
	return xxx_messageInfo_RemoveAnalyzerRes.Size(m)
}
func (m *RemoveAnalyzerRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAnalyzerRes.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAnalyzerRes proto.InternalMessageInfo

func (m *RemoveAnalyzerRes) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateScraperReq)(nil), "pb.svc.provision.CreateScraperReq")
	proto.RegisterType((*CreateScraperRes)(nil), "pb.svc.provision.CreateScraperRes")
	proto.RegisterType((*CreateAnalyzerReq)(nil), "pb.svc.provision.CreateAnalyzerReq")
	proto.RegisterType((*CreateAnalyzerRes)(nil), "pb.svc.provision.CreateAnalyzerRes")
	proto.RegisterType((*GetScraperStatusReq)(nil), "pb.svc.provision.GetScraperStatusReq")
	proto.RegisterType((*GetScraperStatusRes)(nil), "pb.svc.provision.GetScraperStatusRes")
	proto.RegisterType((*GetAnalyzerStatusReq)(nil), "pb.svc.provision.GetAnalyzerStatusReq")
	proto.RegisterType((*GetAnalyzerStatusRes)(nil), "pb.svc.provision.GetAnalyzerStatusRes")
	proto.RegisterType((*RemoveScraperReq)(nil), "pb.svc.provision.RemoveScraperReq")
	proto.RegisterType((*RemoveScraperRes)(nil), "pb.svc.provision.RemoveScraperRes")
	proto.RegisterType((*RemoveAnalyzerReq)(nil), "pb.svc.provision.RemoveAnalyzerReq")
	proto.RegisterType((*RemoveAnalyzerRes)(nil), "pb.svc.provision.RemoveAnalyzerRes")
}

func init() { proto.RegisterFile("pb/svc/provision/provision.proto", fileDescriptor_3a83c3d0d414ae9b) }

var fileDescriptor_3a83c3d0d414ae9b = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdb, 0x4e, 0xf2, 0x40,
	0x10, 0xc7, 0x43, 0xbf, 0x4f, 0xb4, 0x93, 0x48, 0xca, 0x7a, 0x08, 0xa9, 0x5e, 0x90, 0x12, 0x88,
	0x81, 0xd0, 0x82, 0x3c, 0x81, 0x7a, 0x41, 0x88, 0x37, 0x06, 0x2e, 0x4c, 0xb8, 0x91, 0x1e, 0x36,
	0x58, 0x4e, 0x5b, 0x77, 0x4b, 0x09, 0x3e, 0x9b, 0x0f, 0x67, 0xe8, 0x41, 0xda, 0x6e, 0x1b, 0x7a,
	0xc7, 0xce, 0xfe, 0xe6, 0x3f, 0xc3, 0xcc, 0xbf, 0x0b, 0x75, 0xc7, 0xd0, 0x98, 0x67, 0x6a, 0x0e,
	0x25, 0x9e, 0xcd, 0x6c, 0xb2, 0x39, 0xfe, 0x52, 0x1d, 0x4a, 0x5c, 0x82, 0x24, 0xc7, 0x50, 0x99,
	0x67, 0xaa, 0x7f, 0x71, 0x65, 0x06, 0xd2, 0x0b, 0xc5, 0xba, 0x8b, 0x27, 0x26, 0xd5, 0x1d, 0x4c,
	0xc7, 0xf8, 0x0b, 0xd5, 0xe0, 0x7c, 0x89, 0xf7, 0x3b, 0x42, 0xad, 0x5a, 0xa9, 0x5e, 0x7a, 0x10,
	0xc7, 0xd1, 0x11, 0xdd, 0x81, 0xb8, 0x23, 0x74, 0x89, 0xe9, 0x87, 0x6d, 0xd5, 0x04, 0xff, 0xee,
	0x22, 0x08, 0x8c, 0x2c, 0x74, 0x03, 0xe5, 0x05, 0x31, 0x0e, 0x37, 0xff, 0xfc, 0x9b, 0xb3, 0x05,
	0x31, 0x46, 0x96, 0xd2, 0xe6, 0x2a, 0x30, 0x74, 0x0b, 0x65, 0xe6, 0xea, 0xee, 0x96, 0x85, 0x05,
	0xc2, 0x93, 0xf2, 0x0a, 0xd5, 0x80, 0x7d, 0xda, 0xe8, 0xab, 0xfd, 0x77, 0xd0, 0xce, 0x3d, 0x88,
	0x2c, 0x48, 0x1d, 0x45, 0x0d, 0x1d, 0x03, 0xf1, 0x66, 0x85, 0x44, 0xb3, 0x4a, 0x87, 0x17, 0xcb,
	0xaf, 0xdc, 0x84, 0xab, 0x21, 0x76, 0xc3, 0x16, 0x27, 0x7e, 0xec, 0x50, 0xbb, 0x02, 0x82, 0x1d,
	0x15, 0x15, 0x6c, 0x4b, 0xe9, 0x66, 0x61, 0xf9, 0xaa, 0x2d, 0xb8, 0x1e, 0x62, 0x37, 0xaa, 0x9f,
	0x2f, 0xab, 0x66, 0x72, 0xf9, 0xba, 0x0a, 0x48, 0x63, 0xbc, 0x26, 0x5e, 0x7c, 0x6b, 0x69, 0xcd,
	0x36, 0xc7, 0xe4, 0xeb, 0x35, 0xa0, 0x1a, 0xb0, 0xf1, 0xb9, 0xa7, 0x05, 0x3b, 0x3c, 0x94, 0xab,
	0xf8, 0xf8, 0xf3, 0x1f, 0xc4, 0xb7, 0xc8, 0x65, 0xe8, 0x1d, 0x2e, 0x13, 0x1e, 0x40, 0x8a, 0x9a,
	0x76, 0xa2, 0x9a, 0xb6, 0xa1, 0x7c, 0x9a, 0x61, 0x68, 0x0a, 0x95, 0xe4, 0x8e, 0x51, 0x23, 0x2f,
	0x2b, 0xf6, 0xd7, 0xe4, 0x02, 0x10, 0x43, 0x33, 0x90, 0xd2, 0xbb, 0x46, 0x4d, 0x3e, 0x31, 0xc3,
	0x36, 0x72, 0x21, 0x8c, 0x21, 0x13, 0xaa, 0xdc, 0xda, 0x51, 0x2b, 0x33, 0x97, 0xf3, 0x90, 0x5c,
	0x8c, 0x63, 0x87, 0xd9, 0x27, 0x7c, 0x90, 0x35, 0xfb, 0xb4, 0x99, 0xe4, 0xd3, 0x8c, 0x3f, 0xfb,
	0xa4, 0x1f, 0xb2, 0x66, 0xcf, 0xd9, 0x4a, 0x2e, 0x00, 0xb1, 0xe7, 0xc1, 0xb4, 0x3f, 0xb7, 0xdd,
	0xcf, 0xad, 0xa1, 0x9a, 0x64, 0xad, 0xe9, 0xf3, 0x95, 0x6d, 0xe1, 0x7e, 0xaf, 0xa7, 0x59, 0xfa,
	0xb2, 0x1b, 0x7e, 0xdf, 0x5a, 0xfa, 0xb5, 0x33, 0xca, 0xfe, 0x23, 0x37, 0xf8, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x99, 0x54, 0x8d, 0xd6, 0x08, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProvisionClient is the client API for Provision service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProvisionClient interface {
	CreateScraper(ctx context.Context, in *CreateScraperReq, opts ...grpc.CallOption) (*CreateScraperRes, error)
	CreateAnalyzer(ctx context.Context, in *CreateAnalyzerReq, opts ...grpc.CallOption) (*CreateAnalyzerRes, error)
	GetScraperStatus(ctx context.Context, in *GetScraperStatusReq, opts ...grpc.CallOption) (*GetScraperStatusRes, error)
	GetAnalyzerStatus(ctx context.Context, in *GetAnalyzerStatusReq, opts ...grpc.CallOption) (*GetAnalyzerStatusRes, error)
	RemoveScraper(ctx context.Context, in *RemoveScraperReq, opts ...grpc.CallOption) (*RemoveScraperRes, error)
	RemoveAnalyzer(ctx context.Context, in *RemoveAnalyzerReq, opts ...grpc.CallOption) (*RemoveAnalyzerRes, error)
}

type provisionClient struct {
	cc *grpc.ClientConn
}

func NewProvisionClient(cc *grpc.ClientConn) ProvisionClient {
	return &provisionClient{cc}
}

func (c *provisionClient) CreateScraper(ctx context.Context, in *CreateScraperReq, opts ...grpc.CallOption) (*CreateScraperRes, error) {
	out := new(CreateScraperRes)
	err := c.cc.Invoke(ctx, "/pb.svc.provision.Provision/CreateScraper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionClient) CreateAnalyzer(ctx context.Context, in *CreateAnalyzerReq, opts ...grpc.CallOption) (*CreateAnalyzerRes, error) {
	out := new(CreateAnalyzerRes)
	err := c.cc.Invoke(ctx, "/pb.svc.provision.Provision/CreateAnalyzer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionClient) GetScraperStatus(ctx context.Context, in *GetScraperStatusReq, opts ...grpc.CallOption) (*GetScraperStatusRes, error) {
	out := new(GetScraperStatusRes)
	err := c.cc.Invoke(ctx, "/pb.svc.provision.Provision/GetScraperStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionClient) GetAnalyzerStatus(ctx context.Context, in *GetAnalyzerStatusReq, opts ...grpc.CallOption) (*GetAnalyzerStatusRes, error) {
	out := new(GetAnalyzerStatusRes)
	err := c.cc.Invoke(ctx, "/pb.svc.provision.Provision/GetAnalyzerStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionClient) RemoveScraper(ctx context.Context, in *RemoveScraperReq, opts ...grpc.CallOption) (*RemoveScraperRes, error) {
	out := new(RemoveScraperRes)
	err := c.cc.Invoke(ctx, "/pb.svc.provision.Provision/RemoveScraper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionClient) RemoveAnalyzer(ctx context.Context, in *RemoveAnalyzerReq, opts ...grpc.CallOption) (*RemoveAnalyzerRes, error) {
	out := new(RemoveAnalyzerRes)
	err := c.cc.Invoke(ctx, "/pb.svc.provision.Provision/RemoveAnalyzer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionServer is the server API for Provision service.
type ProvisionServer interface {
	CreateScraper(context.Context, *CreateScraperReq) (*CreateScraperRes, error)
	CreateAnalyzer(context.Context, *CreateAnalyzerReq) (*CreateAnalyzerRes, error)
	GetScraperStatus(context.Context, *GetScraperStatusReq) (*GetScraperStatusRes, error)
	GetAnalyzerStatus(context.Context, *GetAnalyzerStatusReq) (*GetAnalyzerStatusRes, error)
	RemoveScraper(context.Context, *RemoveScraperReq) (*RemoveScraperRes, error)
	RemoveAnalyzer(context.Context, *RemoveAnalyzerReq) (*RemoveAnalyzerRes, error)
}

// UnimplementedProvisionServer can be embedded to have forward compatible implementations.
type UnimplementedProvisionServer struct {
}

func (*UnimplementedProvisionServer) CreateScraper(ctx context.Context, req *CreateScraperReq) (*CreateScraperRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScraper not implemented")
}
func (*UnimplementedProvisionServer) CreateAnalyzer(ctx context.Context, req *CreateAnalyzerReq) (*CreateAnalyzerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAnalyzer not implemented")
}
func (*UnimplementedProvisionServer) GetScraperStatus(ctx context.Context, req *GetScraperStatusReq) (*GetScraperStatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScraperStatus not implemented")
}
func (*UnimplementedProvisionServer) GetAnalyzerStatus(ctx context.Context, req *GetAnalyzerStatusReq) (*GetAnalyzerStatusRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnalyzerStatus not implemented")
}
func (*UnimplementedProvisionServer) RemoveScraper(ctx context.Context, req *RemoveScraperReq) (*RemoveScraperRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveScraper not implemented")
}
func (*UnimplementedProvisionServer) RemoveAnalyzer(ctx context.Context, req *RemoveAnalyzerReq) (*RemoveAnalyzerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAnalyzer not implemented")
}

func RegisterProvisionServer(s *grpc.Server, srv ProvisionServer) {
	s.RegisterService(&_Provision_serviceDesc, srv)
}

func _Provision_CreateScraper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScraperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).CreateScraper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.provision.Provision/CreateScraper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).CreateScraper(ctx, req.(*CreateScraperReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provision_CreateAnalyzer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnalyzerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).CreateAnalyzer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.provision.Provision/CreateAnalyzer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).CreateAnalyzer(ctx, req.(*CreateAnalyzerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provision_GetScraperStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScraperStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).GetScraperStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.provision.Provision/GetScraperStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).GetScraperStatus(ctx, req.(*GetScraperStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provision_GetAnalyzerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalyzerStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).GetAnalyzerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.provision.Provision/GetAnalyzerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).GetAnalyzerStatus(ctx, req.(*GetAnalyzerStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provision_RemoveScraper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveScraperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).RemoveScraper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.provision.Provision/RemoveScraper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).RemoveScraper(ctx, req.(*RemoveScraperReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provision_RemoveAnalyzer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAnalyzerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).RemoveAnalyzer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.svc.provision.Provision/RemoveAnalyzer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).RemoveAnalyzer(ctx, req.(*RemoveAnalyzerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provision_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.svc.provision.Provision",
	HandlerType: (*ProvisionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateScraper",
			Handler:    _Provision_CreateScraper_Handler,
		},
		{
			MethodName: "CreateAnalyzer",
			Handler:    _Provision_CreateAnalyzer_Handler,
		},
		{
			MethodName: "GetScraperStatus",
			Handler:    _Provision_GetScraperStatus_Handler,
		},
		{
			MethodName: "GetAnalyzerStatus",
			Handler:    _Provision_GetAnalyzerStatus_Handler,
		},
		{
			MethodName: "RemoveScraper",
			Handler:    _Provision_RemoveScraper_Handler,
		},
		{
			MethodName: "RemoveAnalyzer",
			Handler:    _Provision_RemoveAnalyzer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/svc/provision/provision.proto",
}
