// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: pb/svc/provision/provision.proto

package provision

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveSimilarityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveSimilarityReq) Reset() {
	*x = RemoveSimilarityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSimilarityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSimilarityReq) ProtoMessage() {}

func (x *RemoveSimilarityReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSimilarityReq.ProtoReflect.Descriptor instead.
func (*RemoveSimilarityReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveSimilarityReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveSimilarityRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveSimilarityRes) Reset() {
	*x = RemoveSimilarityRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSimilarityRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSimilarityRes) ProtoMessage() {}

func (x *RemoveSimilarityRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSimilarityRes.ProtoReflect.Descriptor instead.
func (*RemoveSimilarityRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveSimilarityRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateSimilarityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId    string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *CreateSimilarityReq) Reset() {
	*x = CreateSimilarityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSimilarityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSimilarityReq) ProtoMessage() {}

func (x *CreateSimilarityReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSimilarityReq.ProtoReflect.Descriptor instead.
func (*CreateSimilarityReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSimilarityReq) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CreateSimilarityReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CreateSimilarityRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateSimilarityRes) Reset() {
	*x = CreateSimilarityRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSimilarityRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSimilarityRes) ProtoMessage() {}

func (x *CreateSimilarityRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSimilarityRes.ProtoReflect.Descriptor instead.
func (*CreateSimilarityRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSimilarityRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateScraperReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword  string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	WorkerId string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId    string `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Token    string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateScraperReq) Reset() {
	*x = CreateScraperReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScraperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScraperReq) ProtoMessage() {}

func (x *CreateScraperReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScraperReq.ProtoReflect.Descriptor instead.
func (*CreateScraperReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{4}
}

func (x *CreateScraperReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CreateScraperReq) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CreateScraperReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateScraperReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateScraperRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateScraperRes) Reset() {
	*x = CreateScraperRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScraperRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScraperRes) ProtoMessage() {}

func (x *CreateScraperRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScraperRes.ProtoReflect.Descriptor instead.
func (*CreateScraperRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{5}
}

func (x *CreateScraperRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateAnalyzerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	JobId    string `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Keyword  string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *CreateAnalyzerReq) Reset() {
	*x = CreateAnalyzerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnalyzerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnalyzerReq) ProtoMessage() {}

func (x *CreateAnalyzerReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnalyzerReq.ProtoReflect.Descriptor instead.
func (*CreateAnalyzerReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAnalyzerReq) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CreateAnalyzerReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateAnalyzerReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type CreateAnalyzerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateAnalyzerRes) Reset() {
	*x = CreateAnalyzerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnalyzerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnalyzerRes) ProtoMessage() {}

func (x *CreateAnalyzerRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnalyzerRes.ProtoReflect.Descriptor instead.
func (*CreateAnalyzerRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAnalyzerRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetScraperStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetScraperStatusReq) Reset() {
	*x = GetScraperStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScraperStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScraperStatusReq) ProtoMessage() {}

func (x *GetScraperStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScraperStatusReq.ProtoReflect.Descriptor instead.
func (*GetScraperStatusReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{8}
}

func (x *GetScraperStatusReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetScraperStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetScraperStatusRes) Reset() {
	*x = GetScraperStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScraperStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScraperStatusRes) ProtoMessage() {}

func (x *GetScraperStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScraperStatusRes.ProtoReflect.Descriptor instead.
func (*GetScraperStatusRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{9}
}

func (x *GetScraperStatusRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAnalyzerStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAnalyzerStatusReq) Reset() {
	*x = GetAnalyzerStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnalyzerStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyzerStatusReq) ProtoMessage() {}

func (x *GetAnalyzerStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyzerStatusReq.ProtoReflect.Descriptor instead.
func (*GetAnalyzerStatusReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{10}
}

func (x *GetAnalyzerStatusReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAnalyzerStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetAnalyzerStatusRes) Reset() {
	*x = GetAnalyzerStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnalyzerStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyzerStatusRes) ProtoMessage() {}

func (x *GetAnalyzerStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyzerStatusRes.ProtoReflect.Descriptor instead.
func (*GetAnalyzerStatusRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{11}
}

func (x *GetAnalyzerStatusRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemoveScraperReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveScraperReq) Reset() {
	*x = RemoveScraperReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveScraperReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveScraperReq) ProtoMessage() {}

func (x *RemoveScraperReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveScraperReq.ProtoReflect.Descriptor instead.
func (*RemoveScraperReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveScraperReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveScraperRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveScraperRes) Reset() {
	*x = RemoveScraperRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveScraperRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveScraperRes) ProtoMessage() {}

func (x *RemoveScraperRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveScraperRes.ProtoReflect.Descriptor instead.
func (*RemoveScraperRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveScraperRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemoveAnalyzerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveAnalyzerReq) Reset() {
	*x = RemoveAnalyzerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAnalyzerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAnalyzerReq) ProtoMessage() {}

func (x *RemoveAnalyzerReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAnalyzerReq.ProtoReflect.Descriptor instead.
func (*RemoveAnalyzerReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveAnalyzerReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveAnalyzerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoveAnalyzerRes) Reset() {
	*x = RemoveAnalyzerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_provision_provision_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAnalyzerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAnalyzerRes) ProtoMessage() {}

func (x *RemoveAnalyzerRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_provision_provision_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAnalyzerRes.ProtoReflect.Descriptor instead.
func (*RemoveAnalyzerRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_provision_provision_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveAnalyzerRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pb_svc_provision_provision_proto protoreflect.FileDescriptor

var file_pb_svc_provision_provision_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x69,
	0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x49, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x76, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2a, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5f, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2b, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x26, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x7a, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x11, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x80, 0x06, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x57, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x73,
	0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x5a, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x12,
	0x23, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x60, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x25, 0x2e,
	0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69,
	0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x60, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x25, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x12, 0x63, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x26, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x70, 0x62, 0x2e,
	0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x12, 0x57, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x72, 0x61,
	0x70, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x5a, 0x0a, 0x0e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x12, 0x23, 0x2e,
	0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x60, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x25, 0x2e, 0x70, 0x62,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x1a, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x69, 0x6d, 0x69,
	0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x67, 0x6c, 0x69, 0x64, 0x65, 0x31, 0x30,
	0x30, 0x2f, 0x64, 0x61, 0x6b, 0x2d, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x2f, 0x70, 0x62,
	0x2f, 0x73, 0x76, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_provision_provision_proto_rawDescOnce sync.Once
	file_pb_svc_provision_provision_proto_rawDescData = file_pb_svc_provision_provision_proto_rawDesc
)

func file_pb_svc_provision_provision_proto_rawDescGZIP() []byte {
	file_pb_svc_provision_provision_proto_rawDescOnce.Do(func() {
		file_pb_svc_provision_provision_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_provision_provision_proto_rawDescData)
	})
	return file_pb_svc_provision_provision_proto_rawDescData
}

var file_pb_svc_provision_provision_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pb_svc_provision_provision_proto_goTypes = []interface{}{
	(*RemoveSimilarityReq)(nil),  // 0: pb.svc.provision.RemoveSimilarityReq
	(*RemoveSimilarityRes)(nil),  // 1: pb.svc.provision.RemoveSimilarityRes
	(*CreateSimilarityReq)(nil),  // 2: pb.svc.provision.CreateSimilarityReq
	(*CreateSimilarityRes)(nil),  // 3: pb.svc.provision.CreateSimilarityRes
	(*CreateScraperReq)(nil),     // 4: pb.svc.provision.CreateScraperReq
	(*CreateScraperRes)(nil),     // 5: pb.svc.provision.CreateScraperRes
	(*CreateAnalyzerReq)(nil),    // 6: pb.svc.provision.CreateAnalyzerReq
	(*CreateAnalyzerRes)(nil),    // 7: pb.svc.provision.CreateAnalyzerRes
	(*GetScraperStatusReq)(nil),  // 8: pb.svc.provision.GetScraperStatusReq
	(*GetScraperStatusRes)(nil),  // 9: pb.svc.provision.GetScraperStatusRes
	(*GetAnalyzerStatusReq)(nil), // 10: pb.svc.provision.GetAnalyzerStatusReq
	(*GetAnalyzerStatusRes)(nil), // 11: pb.svc.provision.GetAnalyzerStatusRes
	(*RemoveScraperReq)(nil),     // 12: pb.svc.provision.RemoveScraperReq
	(*RemoveScraperRes)(nil),     // 13: pb.svc.provision.RemoveScraperRes
	(*RemoveAnalyzerReq)(nil),    // 14: pb.svc.provision.RemoveAnalyzerReq
	(*RemoveAnalyzerRes)(nil),    // 15: pb.svc.provision.RemoveAnalyzerRes
}
var file_pb_svc_provision_provision_proto_depIdxs = []int32{
	4,  // 0: pb.svc.provision.Provision.CreateScraper:input_type -> pb.svc.provision.CreateScraperReq
	6,  // 1: pb.svc.provision.Provision.CreateAnalyzer:input_type -> pb.svc.provision.CreateAnalyzerReq
	2,  // 2: pb.svc.provision.Provision.CreateSimilarity:input_type -> pb.svc.provision.CreateSimilarityReq
	8,  // 3: pb.svc.provision.Provision.GetScraperStatus:input_type -> pb.svc.provision.GetScraperStatusReq
	10, // 4: pb.svc.provision.Provision.GetAnalyzerStatus:input_type -> pb.svc.provision.GetAnalyzerStatusReq
	12, // 5: pb.svc.provision.Provision.RemoveScraper:input_type -> pb.svc.provision.RemoveScraperReq
	14, // 6: pb.svc.provision.Provision.RemoveAnalyzer:input_type -> pb.svc.provision.RemoveAnalyzerReq
	0,  // 7: pb.svc.provision.Provision.RemoveSimilarity:input_type -> pb.svc.provision.RemoveSimilarityReq
	5,  // 8: pb.svc.provision.Provision.CreateScraper:output_type -> pb.svc.provision.CreateScraperRes
	7,  // 9: pb.svc.provision.Provision.CreateAnalyzer:output_type -> pb.svc.provision.CreateAnalyzerRes
	3,  // 10: pb.svc.provision.Provision.CreateSimilarity:output_type -> pb.svc.provision.CreateSimilarityRes
	9,  // 11: pb.svc.provision.Provision.GetScraperStatus:output_type -> pb.svc.provision.GetScraperStatusRes
	11, // 12: pb.svc.provision.Provision.GetAnalyzerStatus:output_type -> pb.svc.provision.GetAnalyzerStatusRes
	13, // 13: pb.svc.provision.Provision.RemoveScraper:output_type -> pb.svc.provision.RemoveScraperRes
	15, // 14: pb.svc.provision.Provision.RemoveAnalyzer:output_type -> pb.svc.provision.RemoveAnalyzerRes
	1,  // 15: pb.svc.provision.Provision.RemoveSimilarity:output_type -> pb.svc.provision.RemoveSimilarityRes
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pb_svc_provision_provision_proto_init() }
func file_pb_svc_provision_provision_proto_init() {
	if File_pb_svc_provision_provision_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_provision_provision_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSimilarityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSimilarityRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSimilarityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSimilarityRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScraperReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScraperRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnalyzerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnalyzerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScraperStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScraperStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnalyzerStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnalyzerStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveScraperReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveScraperRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAnalyzerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_provision_provision_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAnalyzerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_provision_provision_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_provision_provision_proto_goTypes,
		DependencyIndexes: file_pb_svc_provision_provision_proto_depIdxs,
		MessageInfos:      file_pb_svc_provision_provision_proto_msgTypes,
	}.Build()
	File_pb_svc_provision_provision_proto = out.File
	file_pb_svc_provision_provision_proto_rawDesc = nil
	file_pb_svc_provision_provision_proto_goTypes = nil
	file_pb_svc_provision_provision_proto_depIdxs = nil
}
