// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/unit/worker/worker.proto

package worker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Worker struct {
	WorkerId             string   `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	JobId                string   `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Keyword              string   `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Worker) Reset()         { *m = Worker{} }
func (m *Worker) String() string { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()    {}
func (*Worker) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fb48b142679b3ad, []int{0}
}

func (m *Worker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Worker.Unmarshal(m, b)
}
func (m *Worker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Worker.Marshal(b, m, deterministic)
}
func (m *Worker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Worker.Merge(m, src)
}
func (m *Worker) XXX_Size() int {
	return xxx_messageInfo_Worker.Size(m)
}
func (m *Worker) XXX_DiscardUnknown() {
	xxx_messageInfo_Worker.DiscardUnknown(m)
}

var xxx_messageInfo_Worker proto.InternalMessageInfo

func (m *Worker) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

func (m *Worker) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Worker) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Worker) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*Worker)(nil), "pb.unit.worker.Worker")
}

func init() { proto.RegisterFile("pb/unit/worker/worker.proto", fileDescriptor_0fb48b142679b3ad) }

var fileDescriptor_0fb48b142679b3ad = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x48, 0xd2, 0x2f,
	0xcd, 0xcb, 0x2c, 0xd1, 0x2f, 0xcf, 0x2f, 0xca, 0x4e, 0x2d, 0x82, 0x52, 0x7a, 0x05, 0x45, 0xf9,
	0x25, 0xf9, 0x42, 0x7c, 0x05, 0x49, 0x7a, 0x20, 0x49, 0x3d, 0x88, 0xa8, 0x52, 0x1e, 0x17, 0x5b,
	0x38, 0x98, 0x25, 0x24, 0xcd, 0xc5, 0x09, 0x11, 0x8b, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0xe2, 0x80, 0x08, 0x78, 0xa6, 0x08, 0x89, 0x71, 0xb1, 0x15, 0x97, 0x24, 0x96, 0x94,
	0x16, 0x4b, 0x30, 0x81, 0x65, 0xa0, 0x3c, 0x21, 0x51, 0x2e, 0xb6, 0xac, 0xfc, 0x24, 0x90, 0x0e,
	0x66, 0xb0, 0x38, 0x6b, 0x56, 0x7e, 0x92, 0x67, 0x8a, 0x90, 0x04, 0x17, 0x7b, 0x76, 0x6a, 0x65,
	0x79, 0x7e, 0x51, 0x8a, 0x04, 0x0b, 0x58, 0x1c, 0xc6, 0x75, 0x32, 0x8c, 0xd2, 0x4f, 0xcf, 0x2c,
	0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x4c, 0xcf, 0xc9, 0x4c, 0x49, 0x35, 0x34,
	0x30, 0xd0, 0x4f, 0x49, 0xcc, 0xd6, 0x85, 0xaa, 0xd1, 0x47, 0x75, 0x7f, 0x12, 0x1b, 0xd8, 0xe5,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x23, 0x2f, 0x25, 0xd8, 0x00, 0x00, 0x00,
}
