version: "3.5"

services:
    node:
        build:
            context: .
        networks:
            - docker_network
        #image: node
        ports:
            - 80:80
        environment:
            - GRPCWEBADDR=http://localhost
networks:
    docker_network:
        driver: bridge
        ipam:
            driver: default
