version: "3.5"

services:
    node:
        build:
            context: .
        networks:
            - docker_network
        #image: node
        ports:
            - 4000:3000
networks:
    docker_network:
        driver: bridge
        ipam:
            driver: default
