name: Check mergeable

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read

jobs:
  go_ci:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.13x]
        os: [macos-latest, ubuntu-latest]
    name: lint   
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
